CREATE
(a_0:ARTICLE{title: "CFEOM1, the classic familial form of congenital fibrosis of the extraocular muscles, is genetically heterogeneous but does not result from mutations in ARIX", id: 100320}),
(b_0:ARTICLE{title: "Congenital structural muscle anomalies.", id: None}),
(a_0) -[:REFERENCES]-> (b_0),
(a_0) <-[:REFERENCED_BY]- (b_0),
(d_0:AUTHOR{name: "HW Brown"}) -[:AUTHORS]-> (b_0),
(d_0) <-[:AUTHORED_BY]- (b_0),
(d_1:AUTHOR{name: "surname:JH Allen"}) -[:AUTHORS]-> (b_0),
(d_1) <-[:AUTHORED_BY]- (b_0),
(b_1:ARTICLE{title: "Bilateral Duane's retraction syndrome: A clinical-pathological case report.", id: None}),
(a_0) -[:REFERENCES]-> (b_1),
(a_0) <-[:REFERENCED_BY]- (b_1),
(d_0:AUTHOR{name: "MG Hotchkiss"}) -[:AUTHORS]-> (b_1),
(d_0) <-[:AUTHORED_BY]- (b_1),
(d_1:AUTHOR{name: "NR Miller"}) -[:AUTHORS]-> (b_1),
(d_1) <-[:AUTHORED_BY]- (b_1),
(d_2:AUTHOR{name: "AW Clark"}) -[:AUTHORS]-> (b_1),
(d_2) <-[:AUTHORED_BY]- (b_1),
(d_3:AUTHOR{name: "WG Green"}) -[:AUTHORS]-> (b_1),
(d_3) <-[:AUTHORED_BY]- (b_1),
(b_2:ARTICLE{title: "Unilateral Duane's retraction syndrome (type 1).", id: None}),
(a_0) -[:REFERENCES]-> (b_2),
(a_0) <-[:REFERENCED_BY]- (b_2),
(d_0:AUTHOR{name: "NR Miller"}) -[:AUTHORS]-> (b_2),
(d_0) <-[:AUTHORED_BY]- (b_2),
(d_1:AUTHOR{name: "SM Kiel"}) -[:AUTHORS]-> (b_2),
(d_1) <-[:AUTHORED_BY]- (b_2),
(d_2:AUTHOR{name: "WR Green"}) -[:AUTHORS]-> (b_2),
(d_2) <-[:AUTHORED_BY]- (b_2),
(d_3:AUTHOR{name: "AW Clark"}) -[:AUTHORS]-> (b_2),
(d_3) <-[:AUTHORED_BY]- (b_2),
(b_3:ARTICLE{title: "Oculomotor nerve and muscle abnormalities in congenital fibrosis of the extraocular muscles.", id: 9066352}),
(a_0) -[:REFERENCES]-> (b_3),
(a_0) <-[:REFERENCED_BY]- (b_3),
(d_0:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_3),
(d_0) <-[:AUTHORED_BY]- (b_3),
(d_1:AUTHOR{name: "B Goumernov"}) -[:AUTHORS]-> (b_3),
(d_1) <-[:AUTHORED_BY]- (b_3),
(d_2:AUTHOR{name: "CA McKeown"}) -[:AUTHORS]-> (b_3),
(d_2) <-[:AUTHORED_BY]- (b_3),
(d_3:AUTHOR{name: "M Schatz"}) -[:AUTHORS]-> (b_3),
(d_3) <-[:AUTHORED_BY]- (b_3),
(d_4:AUTHOR{name: "DR Johns"}) -[:AUTHORS]-> (b_3),
(d_4) <-[:AUTHORED_BY]- (b_3),
(d_5:AUTHOR{name: "JD Porter"}) -[:AUTHORS]-> (b_3),
(d_5) <-[:AUTHORED_BY]- (b_3),
(d_6:AUTHOR{name: "AH Beggs"}) -[:AUTHORS]-> (b_3),
(d_6) <-[:AUTHORED_BY]- (b_3),
(b_4:ARTICLE{title: "Homozygous mutations in ARIX(PHOX2A) result in congenital fibrosis of the extraocular muscles type 2.", id: 11600883}),
(a_0) -[:REFERENCES]-> (b_4),
(a_0) <-[:REFERENCED_BY]- (b_4),
(d_0:AUTHOR{name: "M Nakano"}) -[:AUTHORS]-> (b_4),
(d_0) <-[:AUTHORED_BY]- (b_4),
(d_1:AUTHOR{name: "K Yamada"}) -[:AUTHORS]-> (b_4),
(d_1) <-[:AUTHORED_BY]- (b_4),
(d_2:AUTHOR{name: "J Fain"}) -[:AUTHORS]-> (b_4),
(d_2) <-[:AUTHORED_BY]- (b_4),
(d_3:AUTHOR{name: "EC Sener"}) -[:AUTHORS]-> (b_4),
(d_3) <-[:AUTHORED_BY]- (b_4),
(d_4:AUTHOR{name: "CJ Selleck"}) -[:AUTHORS]-> (b_4),
(d_4) <-[:AUTHORED_BY]- (b_4),
(d_5:AUTHOR{name: "AH Awad"}) -[:AUTHORS]-> (b_4),
(d_5) <-[:AUTHORED_BY]- (b_4),
(d_6:AUTHOR{name: "J Zwaan"}) -[:AUTHORS]-> (b_4),
(d_6) <-[:AUTHORED_BY]- (b_4),
(d_7:AUTHOR{name: "PB Mullaney"}) -[:AUTHORS]-> (b_4),
(d_7) <-[:AUTHORED_BY]- (b_4),
(d_8:AUTHOR{name: "TM Bosley"}) -[:AUTHORS]-> (b_4),
(d_8) <-[:AUTHORED_BY]- (b_4),
(d_9:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_4),
(d_9) <-[:AUTHORED_BY]- (b_4),
(b_5:ARTICLE{title: "Mapping a gene for congenital fibrosis of the extraocular muscles to the centromeric region of chromosome 12.", id: 8075644}),
(a_0) -[:REFERENCES]-> (b_5),
(a_0) <-[:REFERENCED_BY]- (b_5),
(d_0:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_5),
(d_0) <-[:AUTHORED_BY]- (b_5),
(d_1:AUTHOR{name: "LM Kunkel"}) -[:AUTHORS]-> (b_5),
(d_1) <-[:AUTHORED_BY]- (b_5),
(d_2:AUTHOR{name: "LA Specht"}) -[:AUTHORS]-> (b_5),
(d_2) <-[:AUTHORED_BY]- (b_5),
(d_3:AUTHOR{name: "AH Beggs"}) -[:AUTHORS]-> (b_5),
(d_3) <-[:AUTHORED_BY]- (b_5),
(b_6:ARTICLE{title: "CFEOM3: a new extraocular congenital fibrosis syndrome that maps to 16q24.2-q24.3.", id: 10393037}),
(a_0) -[:REFERENCES]-> (b_6),
(a_0) <-[:REFERENCED_BY]- (b_6),
(d_0:AUTHOR{name: "E Doherty"}) -[:AUTHORS]-> (b_6),
(d_0) <-[:AUTHORED_BY]- (b_6),
(d_1:AUTHOR{name: "M Macy"}) -[:AUTHORS]-> (b_6),
(d_1) <-[:AUTHORED_BY]- (b_6),
(d_2:AUTHOR{name: "S Wang"}) -[:AUTHORS]-> (b_6),
(d_2) <-[:AUTHORED_BY]- (b_6),
(d_3:AUTHOR{name: "C Dykeman"}) -[:AUTHORS]-> (b_6),
(d_3) <-[:AUTHORED_BY]- (b_6),
(d_4:AUTHOR{name: "M Melanson"}) -[:AUTHORS]-> (b_6),
(d_4) <-[:AUTHORED_BY]- (b_6),
(d_5:AUTHOR{name: "E Engle"}) -[:AUTHORS]-> (b_6),
(d_5) <-[:AUTHORED_BY]- (b_6),
(b_7:ARTICLE{title: "Congenital fibrosis of the extraocular muscles type 2 (CFEOM2), an inherited exotropic strabismus fixus, maps to distal 11q13.", id: 9683611}),
(a_0) -[:REFERENCES]-> (b_7),
(a_0) <-[:REFERENCED_BY]- (b_7),
(d_0:AUTHOR{name: "S Wang"}) -[:AUTHORS]-> (b_7),
(d_0) <-[:AUTHORED_BY]- (b_7),
(d_1:AUTHOR{name: "J Zwaan"}) -[:AUTHORS]-> (b_7),
(d_1) <-[:AUTHORED_BY]- (b_7),
(d_2:AUTHOR{name: "P Mullaney"}) -[:AUTHORS]-> (b_7),
(d_2) <-[:AUTHORED_BY]- (b_7),
(d_3:AUTHOR{name: "M Jabak"}) -[:AUTHORS]-> (b_7),
(d_3) <-[:AUTHORED_BY]- (b_7),
(d_4:AUTHOR{name: "A Al-Awad"}) -[:AUTHORS]-> (b_7),
(d_4) <-[:AUTHORED_BY]- (b_7),
(d_5:AUTHOR{name: "A Beggs"}) -[:AUTHORS]-> (b_7),
(d_5) <-[:AUTHORED_BY]- (b_7),
(d_6:AUTHOR{name: "E Engle"}) -[:AUTHORS]-> (b_7),
(d_6) <-[:AUTHORED_BY]- (b_7),
(b_8:ARTICLE{title: "Erfahrungen uber den strabismus und die Muskeldurchschneidung am Auge in physiologischpathologischer und therapeutischer Beziehung.", id: None}),
(a_0) -[:REFERENCES]-> (b_8),
(a_0) <-[:REFERENCED_BY]- (b_8),
(d_0:AUTHOR{name: "M Baumgarten"}) -[:AUTHORS]-> (b_8),
(d_0) <-[:AUTHORED_BY]- (b_8),
(b_9:ARTICLE{title: "Ueber angeborenen vererbten Beweglichkeits – Defect der Augen.", id: None}),
(a_0) -[:REFERENCES]-> (b_9),
(a_0) <-[:REFERENCED_BY]- (b_9),
(d_0:AUTHOR{name: "G Heuck"}) -[:AUTHORS]-> (b_9),
(d_0) <-[:AUTHORED_BY]- (b_9),
(b_10:ARTICLE{title: "Locus heterogeneity in autosomal dominant congenital external ophthalmoplegia.", id: 9863593}),
(a_0) -[:REFERENCES]-> (b_10),
(a_0) <-[:REFERENCED_BY]- (b_10),
(d_0:AUTHOR{name: "G Black"}) -[:AUTHORS]-> (b_10),
(d_0) <-[:AUTHORED_BY]- (b_10),
(d_1:AUTHOR{name: "R Perveen"}) -[:AUTHORS]-> (b_10),
(d_1) <-[:AUTHORED_BY]- (b_10),
(d_2:AUTHOR{name: "E Hatchwell"}) -[:AUTHORS]-> (b_10),
(d_2) <-[:AUTHORED_BY]- (b_10),
(d_3:AUTHOR{name: "A Reck"}) -[:AUTHORS]-> (b_10),
(d_3) <-[:AUTHORED_BY]- (b_10),
(d_4:AUTHOR{name: "J Clayton-Smith"}) -[:AUTHORS]-> (b_10),
(d_4) <-[:AUTHORED_BY]- (b_10),
(b_11:ARTICLE{title: "Hereditary ophthalmoplegia in five generations.", id: None}),
(a_0) -[:REFERENCES]-> (b_11),
(a_0) <-[:REFERENCED_BY]- (b_11),
(d_0:AUTHOR{name: "AA Bradburn"}) -[:AUTHORS]-> (b_11),
(d_0) <-[:AUTHORED_BY]- (b_11),
(b_12:ARTICLE{title: "A familial musculo-fascial anomaly.", id: 5226573}),
(a_0) -[:REFERENCES]-> (b_12),
(a_0) <-[:REFERENCED_BY]- (b_12),
(d_0:AUTHOR{name: "GV Catford"}) -[:AUTHORS]-> (b_12),
(d_0) <-[:AUTHORED_BY]- (b_12),
(b_13:ARTICLE{title: "Congenital familial external ophthalmoplegia with co-contraction.", id: 6545392}),
(a_0) -[:REFERENCES]-> (b_13),
(a_0) <-[:REFERENCED_BY]- (b_13),
(d_0:AUTHOR{name: "GW Cibis"}) -[:AUTHORS]-> (b_13),
(d_0) <-[:AUTHORED_BY]- (b_13),
(b_14:ARTICLE{title: "Congenital fibrosis of the extraocular muscles (autosomal dominant congenital external ophthalmoplegia): genetic homogeneity, linkage refinement, and physical mapping on chromosome 12.", id: 7485159}),
(a_0) -[:REFERENCES]-> (b_14),
(a_0) <-[:REFERENCED_BY]- (b_14),
(d_0:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_14),
(d_0) <-[:AUTHORED_BY]- (b_14),
(d_1:AUTHOR{name: "I Marondel"}) -[:AUTHORS]-> (b_14),
(d_1) <-[:AUTHORED_BY]- (b_14),
(d_2:AUTHOR{name: "WA Houtman"}) -[:AUTHORS]-> (b_14),
(d_2) <-[:AUTHORED_BY]- (b_14),
(d_3:AUTHOR{name: "B de Vries"}) -[:AUTHORS]-> (b_14),
(d_3) <-[:AUTHORED_BY]- (b_14),
(d_4:AUTHOR{name: "A Lowenstein"}) -[:AUTHORS]-> (b_14),
(d_4) <-[:AUTHORED_BY]- (b_14),
(d_5:AUTHOR{name: "M Lazar"}) -[:AUTHORS]-> (b_14),
(d_5) <-[:AUTHORED_BY]- (b_14),
(d_6:AUTHOR{name: "DC Ward"}) -[:AUTHORS]-> (b_14),
(d_6) <-[:AUTHORED_BY]- (b_14),
(d_7:AUTHOR{name: "R Kucherlapati"}) -[:AUTHORS]-> (b_14),
(d_7) <-[:AUTHORED_BY]- (b_14),
(d_8:AUTHOR{name: "AH Beggs"}) -[:AUTHORS]-> (b_14),
(d_8) <-[:AUTHORED_BY]- (b_14),
(b_15:ARTICLE{title: "Congenital fibrosis of the extraocular muscles.", id: 739362}),
(a_0) -[:REFERENCES]-> (b_15),
(a_0) <-[:REFERENCED_BY]- (b_15),
(d_0:AUTHOR{name: "RD Harley"}) -[:AUTHORS]-> (b_15),
(d_0) <-[:AUTHORED_BY]- (b_15),
(d_1:AUTHOR{name: "MM Rodrigues"}) -[:AUTHORS]-> (b_15),
(d_1) <-[:AUTHORED_BY]- (b_15),
(d_2:AUTHOR{name: "JS Crawford"}) -[:AUTHORS]-> (b_15),
(d_2) <-[:AUTHORED_BY]- (b_15),
(b_16:ARTICLE{title: "Hereditary congenital external ophthalmoplegia.", id: 3587876}),
(a_0) -[:REFERENCES]-> (b_16),
(a_0) <-[:REFERENCED_BY]- (b_16),
(d_0:AUTHOR{name: "WA Houtman"}) -[:AUTHORS]-> (b_16),
(d_0) <-[:AUTHORED_BY]- (b_16),
(d_1:AUTHOR{name: "TW vanWeerden"}) -[:AUTHORS]-> (b_16),
(d_1) <-[:AUTHORED_BY]- (b_16),
(d_2:AUTHOR{name: "PH Robinson"}) -[:AUTHORS]-> (b_16),
(d_2) <-[:AUTHORED_BY]- (b_16),
(d_3:AUTHOR{name: "B deVries"}) -[:AUTHORS]-> (b_16),
(d_3) <-[:AUTHORED_BY]- (b_16),
(d_4:AUTHOR{name: "TU Hoogenraad"}) -[:AUTHORS]-> (b_16),
(d_4) <-[:AUTHORED_BY]- (b_16),
(b_17:ARTICLE{title: "Congenital fibrosis of the extraocular muscles; a report of six cases.", id: None}),
(a_0) -[:REFERENCES]-> (b_17),
(a_0) <-[:REFERENCED_BY]- (b_17),
(d_0:AUTHOR{name: "RC Laughlin"}) -[:AUTHORS]-> (b_17),
(d_0) <-[:AUTHORED_BY]- (b_17),
(b_18:ARTICLE{title: "Congenital static familial ophthalmoplegia.", id: 14415239}),
(a_0) -[:REFERENCES]-> (b_18),
(a_0) <-[:REFERENCED_BY]- (b_18),
(d_0:AUTHOR{name: "F Lees"}) -[:AUTHORS]-> (b_18),
(d_0) <-[:AUTHORED_BY]- (b_18),
(b_20:ARTICLE{title: "Congenital fibrosis of the extraocular muscles: Report of 24 cases illustrating the clinical spectrum and surgical management.", id: None}),
(a_0) -[:REFERENCES]-> (b_20),
(a_0) <-[:REFERENCED_BY]- (b_20),
(d_0:AUTHOR{name: "E Traboulsi"}) -[:AUTHORS]-> (b_20),
(d_0) <-[:AUTHORED_BY]- (b_20),
(d_1:AUTHOR{name: "M Jaafar"}) -[:AUTHORS]-> (b_20),
(d_1) <-[:AUTHORED_BY]- (b_20),
(d_2:AUTHOR{name: "H Kattan"}) -[:AUTHORS]-> (b_20),
(d_2) <-[:AUTHORED_BY]- (b_20),
(d_3:AUTHOR{name: "M Parks"}) -[:AUTHORS]-> (b_20),
(d_3) <-[:AUTHORED_BY]- (b_20),
(b_21:ARTICLE{title: "Development of noradrenergic neurons in the zebrafish hindbrain requires BMP, FGF8, and the homeodomain protein soulless/Phox2a.", id: 10595509}),
(a_0) -[:REFERENCES]-> (b_21),
(a_0) <-[:REFERENCED_BY]- (b_21),
(d_0:AUTHOR{name: "S Guo"}) -[:AUTHORS]-> (b_21),
(d_0) <-[:AUTHORED_BY]- (b_21),
(d_1:AUTHOR{name: "J Brush"}) -[:AUTHORS]-> (b_21),
(d_1) <-[:AUTHORED_BY]- (b_21),
(d_2:AUTHOR{name: "H Teraoka"}) -[:AUTHORS]-> (b_21),
(d_2) <-[:AUTHORED_BY]- (b_21),
(d_3:AUTHOR{name: "A Goddard"}) -[:AUTHORS]-> (b_21),
(d_3) <-[:AUTHORED_BY]- (b_21),
(d_4:AUTHOR{name: "SW Wilson"}) -[:AUTHORS]-> (b_21),
(d_4) <-[:AUTHORED_BY]- (b_21),
(d_5:AUTHOR{name: "MC Mullins"}) -[:AUTHORS]-> (b_21),
(d_5) <-[:AUTHORED_BY]- (b_21),
(d_6:AUTHOR{name: "A Rosenthal"}) -[:AUTHORS]-> (b_21),
(d_6) <-[:AUTHORED_BY]- (b_21),
(b_22:ARTICLE{title: "Expression and interactions of the two closely related homeobox genes Phox2a and Phox2b during neurogenesis.", id: 9374403}),
(a_0) -[:REFERENCES]-> (b_22),
(a_0) <-[:REFERENCED_BY]- (b_22),
(d_0:AUTHOR{name: "A Pattyn"}) -[:AUTHORS]-> (b_22),
(d_0) <-[:AUTHORED_BY]- (b_22),
(d_1:AUTHOR{name: "X Morin"}) -[:AUTHORS]-> (b_22),
(d_1) <-[:AUTHORED_BY]- (b_22),
(d_2:AUTHOR{name: "H Cremer"}) -[:AUTHORS]-> (b_22),
(d_2) <-[:AUTHORED_BY]- (b_22),
(d_3:AUTHOR{name: "C Goridis"}) -[:AUTHORS]-> (b_22),
(d_3) <-[:AUTHORED_BY]- (b_22),
(d_4:AUTHOR{name: "JF Brunet"}) -[:AUTHORS]-> (b_22),
(d_4) <-[:AUTHORED_BY]- (b_22),
(b_23:ARTICLE{title: "New clinical variation of a fibrosis syndrome in a Turkish family maps to the CFEOM1 locus on chromosome 12.", id: None}),
(a_0) -[:REFERENCES]-> (b_23),
(a_0) <-[:REFERENCED_BY]- (b_23),
(d_0:AUTHOR{name: "EC Sener"}) -[:AUTHORS]-> (b_23),
(d_0) <-[:AUTHORED_BY]- (b_23),
(d_1:AUTHOR{name: "BA Lee"}) -[:AUTHORS]-> (b_23),
(d_1) <-[:AUTHORED_BY]- (b_23),
(d_2:AUTHOR{name: "B Turgut"}) -[:AUTHORS]-> (b_23),
(d_2) <-[:AUTHORED_BY]- (b_23),
(d_3:AUTHOR{name: "AN Akarsu"}) -[:AUTHORS]-> (b_23),
(d_3) <-[:AUTHORED_BY]- (b_23),
(d_4:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_23),
(d_4) <-[:AUTHORED_BY]- (b_23),
(b_24:ARTICLE{title: "Congenital fibrosis of the extraocular muscles associated with cortical dysplasia and maldevelopment of the basal ganglia.", id: 11425694}),
(a_0) -[:REFERENCES]-> (b_24),
(a_0) <-[:REFERENCED_BY]- (b_24),
(d_0:AUTHOR{name: "MP Flaherty"}) -[:AUTHORS]-> (b_24),
(d_0) <-[:AUTHORED_BY]- (b_24),
(d_1:AUTHOR{name: "P Grattan-Smith"}) -[:AUTHORS]-> (b_24),
(d_1) <-[:AUTHORED_BY]- (b_24),
(d_2:AUTHOR{name: "A Steinberg"}) -[:AUTHORS]-> (b_24),
(d_2) <-[:AUTHORED_BY]- (b_24),
(d_3:AUTHOR{name: "R Jamieson"}) -[:AUTHORS]-> (b_24),
(d_3) <-[:AUTHORED_BY]- (b_24),
(d_4:AUTHOR{name: "EC Engle"}) -[:AUTHORS]-> (b_24),
(d_4) <-[:AUTHORED_BY]- (b_24),
(b_25:ARTICLE{title: "Congenital fibrosis of the extraocular muscles type 1: MRI and clinical findings.", id: None}),
(a_0) -[:REFERENCES]-> (b_25),
(a_0) <-[:REFERENCED_BY]- (b_25),
(d_0:AUTHOR{name: "B Hart"}) -[:AUTHORS]-> (b_25),
(d_0) <-[:AUTHORED_BY]- (b_25),
(d_1:AUTHOR{name: "T Carlow"}) -[:AUTHORS]-> (b_25),
(d_1) <-[:AUTHORED_BY]- (b_25),
(d_2:AUTHOR{name: "E Engle"}) -[:AUTHORS]-> (b_25),
(d_2) <-[:AUTHORED_BY]- (b_25),
(b_26:ARTICLE{title: "Faster Sequential Genetic Linkage Computations.", id: 8317490}),
(a_0) -[:REFERENCES]-> (b_26),
(a_0) <-[:REFERENCED_BY]- (b_26),
(d_0:AUTHOR{name: "RW;suffix:Jr Cottingham"}) -[:AUTHORS]-> (b_26),
(d_0) <-[:AUTHORED_BY]- (b_26),
(d_1:AUTHOR{name: "RM Idury"}) -[:AUTHORS]-> (b_26),
(d_1) <-[:AUTHORED_BY]- (b_26),
(d_2:AUTHOR{name: "AA Schäffer"}) -[:AUTHORS]-> (b_26),
(d_2) <-[:AUTHORED_BY]- (b_26),
(c_0:AUTHOR{name: "Elizabeth C Engle"}) -[:AUTHORS]-> (a_0),
(c_0) <-[:AUTHORED_BY]- (a_0),
(c_1:AUTHOR{name: "Nathalie McIntosh"}) -[:AUTHORS]-> (a_0),
(c_1) <-[:AUTHORED_BY]- (a_0),
(c_2:AUTHOR{name: "Naomichi Matsumoto"}) -[:AUTHORS]-> (a_0),
(c_2) <-[:AUTHORED_BY]- (a_0),
(c_3:AUTHOR{name: "Nakamichi Saito"}) -[:AUTHORS]-> (a_0),
(c_3) <-[:AUTHORED_BY]- (a_0),
(c_4:AUTHOR{name: "Mary Louise Z Collins"}) -[:AUTHORS]-> (a_0),
(c_4) <-[:AUTHORED_BY]- (a_0),
(c_5:AUTHOR{name: "Lisa Morris"}) -[:AUTHORS]-> (a_0),
(c_5) <-[:AUTHORED_BY]- (a_0),
(c_6:AUTHOR{name: "Monte Del Monte"}) -[:AUTHORS]-> (a_0),
(c_6) <-[:AUTHORED_BY]- (a_0),
(c_7:AUTHOR{name: "Adriano Magli"}) -[:AUTHORS]-> (a_0),
(c_7) <-[:AUTHORED_BY]- (a_0),
(c_8:AUTHOR{name: "Teresa de Berardinis"}) -[:AUTHORS]-> (a_0),
(c_8) <-[:AUTHORED_BY]- (a_0),
(c_9:AUTHOR{name: "Koki Yamada"}) -[:AUTHORS]-> (a_0),
(c_9) <-[:AUTHORED_BY]- (a_0),
(c_10:AUTHOR{name: "Bjorn A Lee"}) -[:AUTHORS]-> (a_0),
(c_10) <-[:AUTHORED_BY]- (a_0),
(c_11:AUTHOR{name: "Roger Johnson"}) -[:AUTHORS]-> (a_0),
(c_11) <-[:AUTHORED_BY]- (a_0),
(c_12:AUTHOR{name: "Michael O'Keefe"}) -[:AUTHORS]-> (a_0),
(c_12) <-[:AUTHORED_BY]- (a_0),
(c_13:AUTHOR{name: "Robert Letson"}) -[:AUTHORS]-> (a_0),
(c_13) <-[:AUTHORED_BY]- (a_0),
(c_14:AUTHOR{name: "Arnold London"}) -[:AUTHORS]-> (a_0),
(c_14) <-[:AUTHORED_BY]- (a_0),
(c_15:AUTHOR{name: "Evan Ballard"}) -[:AUTHORS]-> (a_0),
(c_15) <-[:AUTHORED_BY]- (a_0),
(c_16:AUTHOR{name: "Mark Ruttum"}) -[:AUTHORS]-> (a_0),
(c_16) <-[:AUTHORED_BY]- (a_0),

(a_1:ARTICLE{title: "Role of arginine and its methylated derivatives in cancer biology and treatment", id: 101227}),
(b_0:ARTICLE{title: "Studies of culture media for the growth of human tumour cells.", id: None}),
(a_1) -[:REFERENCES]-> (b_0),
(a_1) <-[:REFERENCED_BY]- (b_0),
(d_0:AUTHOR{name: "J Hanss"}) -[:AUTHORS]-> (b_0),
(d_0) <-[:AUTHORED_BY]- (b_0),
(d_1:AUTHOR{name: "GE Moore"}) -[:AUTHORS]-> (b_0),
(d_1) <-[:AUTHORED_BY]- (b_0),
(b_1:ARTICLE{title: "The effect of arginase on the retardation of tumour growth.", id: 14316215}),
(a_1) -[:REFERENCES]-> (b_1),
(a_1) <-[:REFERENCED_BY]- (b_1),
(d_0:AUTHOR{name: "SJ Bach"}) -[:AUTHORS]-> (b_1),
(d_0) <-[:AUTHORED_BY]- (b_1),
(d_1:AUTHOR{name: "D Swaine"}) -[:AUTHORS]-> (b_1),
(d_1) <-[:AUTHORED_BY]- (b_1),
(b_2:ARTICLE{title: "Inhibition of the growth of cultured cells by arginase and soluble proteins from mouse skin.", id: 4306504}),
(a_1) -[:REFERENCES]-> (b_2),
(a_1) <-[:REFERENCED_BY]- (b_2),
(d_0:AUTHOR{name: "M Umeda"}) -[:AUTHORS]-> (b_2),
(d_0) <-[:AUTHORED_BY]- (b_2),
(d_1:AUTHOR{name: "D Diringer"}) -[:AUTHORS]-> (b_2),
(d_1) <-[:AUTHORED_BY]- (b_2),
(d_2:AUTHOR{name: "C Heidelberger"}) -[:AUTHORS]-> (b_2),
(d_2) <-[:AUTHORED_BY]- (b_2),
(b_3:ARTICLE{title: "Difference of the inhibitor of DNA synthesis in liver extract from liver arginase.", id: 5763981}),
(a_1) -[:REFERENCES]-> (b_3),
(a_1) <-[:REFERENCED_BY]- (b_3),
(d_0:AUTHOR{name: "H Otsuka"}) -[:AUTHORS]-> (b_3),
(d_0) <-[:AUTHORED_BY]- (b_3),
(b_4:ARTICLE{title: "Activity in human breast cancer cell lines: N(omega)-hydroxy-L-Arg selectively inhibits cell proliferation and induces apoptosis in MDA-MB-468 cells.", id: 10866325}),
(a_1) -[:REFERENCES]-> (b_4),
(a_1) <-[:REFERENCED_BY]- (b_4),
(d_0:AUTHOR{name: "R Singh"}) -[:AUTHORS]-> (b_4),
(d_0) <-[:AUTHORED_BY]- (b_4),
(d_1:AUTHOR{name: "S Pervin"}) -[:AUTHORS]-> (b_4),
(d_1) <-[:AUTHORED_BY]- (b_4),
(d_2:AUTHOR{name: "A Karimi"}) -[:AUTHORS]-> (b_4),
(d_2) <-[:AUTHORED_BY]- (b_4),
(d_3:AUTHOR{name: "S Cederbaum"}) -[:AUTHORS]-> (b_4),
(d_3) <-[:AUTHORED_BY]- (b_4),
(d_4:AUTHOR{name: "G Chaudhuri"}) -[:AUTHORS]-> (b_4),
(d_4) <-[:AUTHORED_BY]- (b_4),
(b_5:ARTICLE{title: "Influence of the deprivation of a single amino acid on cellular proliferation and survival in rat 3Y1 fibroblasts and their derivatives transformed by a wide variety of agents.", id: 2844831}),
(a_1) -[:REFERENCES]-> (b_5),
(a_1) <-[:REFERENCED_BY]- (b_5),
(d_0:AUTHOR{name: "H Tanaka"}) -[:AUTHORS]-> (b_5),
(d_0) <-[:AUTHORED_BY]- (b_5),
(d_1:AUTHOR{name: "H Zaitsu"}) -[:AUTHORS]-> (b_5),
(d_1) <-[:AUTHORED_BY]- (b_5),
(d_2:AUTHOR{name: "K Onodera"}) -[:AUTHORS]-> (b_5),
(d_2) <-[:AUTHORED_BY]- (b_5),
(d_3:AUTHOR{name: "G Kimura"}) -[:AUTHORS]-> (b_5),
(d_3) <-[:AUTHORED_BY]- (b_5),
(b_6:ARTICLE{title: "Single amino acid (Arg) restriction: growth and death of cultured HeLa and human diploid fibroblasts.", id: 10846151}),
(a_1) -[:REFERENCES]-> (b_6),
(a_1) <-[:REFERENCED_BY]- (b_6),
(d_0:AUTHOR{name: "DN Wheatley"}) -[:AUTHORS]-> (b_6),
(d_0) <-[:AUTHORED_BY]- (b_6),
(d_1:AUTHOR{name: "L Scott"}) -[:AUTHORS]-> (b_6),
(d_1) <-[:AUTHORED_BY]- (b_6),
(d_2:AUTHOR{name: "J Lamb"}) -[:AUTHORS]-> (b_6),
(d_2) <-[:AUTHORED_BY]- (b_6),
(d_3:AUTHOR{name: "S Smith"}) -[:AUTHORS]-> (b_6),
(d_3) <-[:AUTHORED_BY]- (b_6),
(b_7:ARTICLE{title: "Arginine deprivation and tumour cell death: in vitro and in vivo studies.", id: None}),
(a_1) -[:REFERENCES]-> (b_7),
(a_1) <-[:REFERENCED_BY]- (b_7),
(d_0:AUTHOR{name: "LA Scott"}) -[:AUTHORS]-> (b_7),
(d_0) <-[:AUTHORED_BY]- (b_7),
(b_8:ARTICLE{title: "effects of arginine deficiency on lymphoma cells.", id: None}),
(a_1) -[:REFERENCES]-> (b_8),
(a_1) <-[:REFERENCED_BY]- (b_8),
(d_0:AUTHOR{name: "Storr JM"}) -[:AUTHORS]-> (b_8),
(d_0) <-[:AUTHORED_BY]- (b_8),
(d_1:AUTHOR{name: "AF Button"}) -[:AUTHORS]-> (b_8),
(d_1) <-[:AUTHORED_BY]- (b_8),
(b_9:ARTICLE{title: "Single amino acid (arginine) deprivation: rapid and selective death of cultured transformed and malignant cells.", id: None}),
(a_1) -[:REFERENCES]-> (b_9),
(a_1) <-[:REFERENCED_BY]- (b_9),
(d_0:AUTHOR{name: "L Scott"}) -[:AUTHORS]-> (b_9),
(d_0) <-[:AUTHORED_BY]- (b_9),
(d_1:AUTHOR{name: "J Lamb"}) -[:AUTHORS]-> (b_9),
(d_1) <-[:AUTHORED_BY]- (b_9),
(d_2:AUTHOR{name: "S Smith"}) -[:AUTHORS]-> (b_9),
(d_2) <-[:AUTHORED_BY]- (b_9),
(d_3:AUTHOR{name: "DN Wheatley"}) -[:AUTHORS]-> (b_9),
(d_3) <-[:AUTHORED_BY]- (b_9),
(b_10:ARTICLE{title: "Single amino acid (arginine) deprivation induces G1 arrest associated with inhibition of cdk4 expression.", id: 10694439}),
(a_1) -[:REFERENCES]-> (b_10),
(a_1) <-[:REFERENCED_BY]- (b_10),
(d_0:AUTHOR{name: "J Lamb"}) -[:AUTHORS]-> (b_10),
(d_0) <-[:AUTHORED_BY]- (b_10),
(d_1:AUTHOR{name: "DN Wheatley"}) -[:AUTHORS]-> (b_10),
(d_1) <-[:AUTHORED_BY]- (b_10),
(b_11:ARTICLE{title: "Depletion of dietary arginine inhibits growth of metastatic tumor.", id: 1747050}),
(a_1) -[:REFERENCES]-> (b_11),
(a_1) <-[:REFERENCED_BY]- (b_11),
(d_0:AUTHOR{name: "TJ Yeatman"}) -[:AUTHORS]-> (b_11),
(d_0) <-[:AUTHORED_BY]- (b_11),
(d_1:AUTHOR{name: "GL Risely"}) -[:AUTHORS]-> (b_11),
(d_1) <-[:AUTHORED_BY]- (b_11),
(d_2:AUTHOR{name: "ME Brunson"}) -[:AUTHORS]-> (b_11),
(d_2) <-[:AUTHORED_BY]- (b_11),
(b_12:ARTICLE{title: "L-arginine and malignant disease: a potential therapeutic role?", id: 8181591}),
(a_1) -[:REFERENCES]-> (b_12),
(a_1) <-[:REFERENCED_BY]- (b_12),
(d_0:AUTHOR{name: "J Brittenden"}) -[:AUTHORS]-> (b_12),
(d_0) <-[:AUTHORED_BY]- (b_12),
(d_1:AUTHOR{name: "SD Heys"}) -[:AUTHORS]-> (b_12),
(d_1) <-[:AUTHORED_BY]- (b_12),
(d_2:AUTHOR{name: "O Eremin"}) -[:AUTHORS]-> (b_12),
(d_2) <-[:AUTHORED_BY]- (b_12),
(b_13:ARTICLE{title: "Effect of fish oil, arginine, and doxorubicin chemotherapy on remission and survival time for dogs with lymphoma: A double-blind, randomised placebo-controlled study.", id: 10760770}),
(a_1) -[:REFERENCES]-> (b_13),
(a_1) <-[:REFERENCED_BY]- (b_13),
(d_0:AUTHOR{name: "GK Ogilvie"}) -[:AUTHORS]-> (b_13),
(d_0) <-[:AUTHORED_BY]- (b_13),
(d_1:AUTHOR{name: "MJ Fettman"}) -[:AUTHORS]-> (b_13),
(d_1) <-[:AUTHORED_BY]- (b_13),
(d_2:AUTHOR{name: "CH Mallinckrodt"}) -[:AUTHORS]-> (b_13),
(d_2) <-[:AUTHORED_BY]- (b_13),
(d_3:AUTHOR{name: "JA Walton"}) -[:AUTHORS]-> (b_13),
(d_3) <-[:AUTHORED_BY]- (b_13),
(d_4:AUTHOR{name: "RA Hansen"}) -[:AUTHORS]-> (b_13),
(d_4) <-[:AUTHORED_BY]- (b_13),
(d_5:AUTHOR{name: "DJ Davenport"}) -[:AUTHORS]-> (b_13),
(d_5) <-[:AUTHORED_BY]- (b_13),
(d_6:AUTHOR{name: "KL Gross"}) -[:AUTHORS]-> (b_13),
(d_6) <-[:AUTHORED_BY]- (b_13),
(d_7:AUTHOR{name: "KL Richardson"}) -[:AUTHORS]-> (b_13),
(d_7) <-[:AUTHORED_BY]- (b_13),
(d_8:AUTHOR{name: "Q Rogers"}) -[:AUTHORS]-> (b_13),
(d_8) <-[:AUTHORED_BY]- (b_13),
(d_9:AUTHOR{name: "MS Hand"}) -[:AUTHORS]-> (b_13),
(d_9) <-[:AUTHORED_BY]- (b_13),
(b_14:ARTICLE{title: "Effect of arginine on growth of squamous cell carcinoma in the CH3/KM mouse.", id: 7840927}),
(a_1) -[:REFERENCES]-> (b_14),
(a_1) <-[:REFERENCED_BY]- (b_14),
(d_0:AUTHOR{name: "JE Hester"}) -[:AUTHORS]-> (b_14),
(d_0) <-[:AUTHORED_BY]- (b_14),
(d_1:AUTHOR{name: "WE Fee"}) -[:AUTHORS]-> (b_14),
(d_1) <-[:AUTHORED_BY]- (b_14),
(b_15:ARTICLE{title: "Amino acid nutrition and immune function in tumour-bearing rats: A comparison of glutamine, arginine- and ornithine 2-oxoglutarate-supplemented diets.", id: 10585893}),
(a_1) -[:REFERENCES]-> (b_15),
(a_1) <-[:REFERENCED_BY]- (b_15),
(d_0:AUTHOR{name: "LE Robinson"}) -[:AUTHORS]-> (b_15),
(d_0) <-[:AUTHORED_BY]- (b_15),
(d_1:AUTHOR{name: "FI Bussiere"}) -[:AUTHORS]-> (b_15),
(d_1) <-[:AUTHORED_BY]- (b_15),
(d_2:AUTHOR{name: "J Le-Boucher"}) -[:AUTHORS]-> (b_15),
(d_2) <-[:AUTHORED_BY]- (b_15),
(d_3:AUTHOR{name: "MC Farges"}) -[:AUTHORS]-> (b_15),
(d_3) <-[:AUTHORED_BY]- (b_15),
(d_4:AUTHOR{name: "LA Cynober"}) -[:AUTHORS]-> (b_15),
(d_4) <-[:AUTHORED_BY]- (b_15),
(d_5:AUTHOR{name: "CJ Field"}) -[:AUTHORS]-> (b_15),
(d_5) <-[:AUTHORED_BY]- (b_15),
(d_6:AUTHOR{name: "VE Baracos"}) -[:AUTHORS]-> (b_15),
(d_6) <-[:AUTHORED_BY]- (b_15),
(b_16:ARTICLE{title: "Prevention by arginine glutamate of the carcinogenicity of acidamide in rats.", id: 4304688}),
(a_1) -[:REFERENCES]-> (b_16),
(a_1) <-[:REFERENCED_BY]- (b_16),
(d_0:AUTHOR{name: "JH Weisberger"}) -[:AUTHORS]-> (b_16),
(d_0) <-[:AUTHORED_BY]- (b_16),
(d_1:AUTHOR{name: "RS Yamamoto"}) -[:AUTHORS]-> (b_16),
(d_1) <-[:AUTHORED_BY]- (b_16),
(d_2:AUTHOR{name: "RM Glass"}) -[:AUTHORS]-> (b_16),
(d_2) <-[:AUTHORED_BY]- (b_16),
(d_3:AUTHOR{name: "HH Frankel"}) -[:AUTHORS]-> (b_16),
(d_3) <-[:AUTHORED_BY]- (b_16),
(b_17:ARTICLE{title: "Arginine induces apoptosis and gene expression of pancreatitis-associated protein (PAP) in rat pancreatic acinar AR4-2J cells.", id: 10630385}),
(a_1) -[:REFERENCES]-> (b_17),
(a_1) <-[:REFERENCED_BY]- (b_17),
(d_0:AUTHOR{name: "Y Motoo"}) -[:AUTHORS]-> (b_17),
(d_0) <-[:AUTHORED_BY]- (b_17),
(d_1:AUTHOR{name: "K Taga"}) -[:AUTHORS]-> (b_17),
(d_1) <-[:AUTHORED_BY]- (b_17),
(d_2:AUTHOR{name: "SB Su"}) -[:AUTHORS]-> (b_17),
(d_2) <-[:AUTHORED_BY]- (b_17),
(d_3:AUTHOR{name: "MJ Xie"}) -[:AUTHORS]-> (b_17),
(d_3) <-[:AUTHORED_BY]- (b_17),
(d_4:AUTHOR{name: "N Sawabu"}) -[:AUTHORS]-> (b_17),
(d_4) <-[:AUTHORED_BY]- (b_17),
(b_18:ARTICLE{title: "Arginine-rich anti-vascular endothelial growth factor peptides inhibit tumor growth and metastasis by blocking angiogenesis.", id: 10788475}),
(a_1) -[:REFERENCES]-> (b_18),
(a_1) <-[:REFERENCED_BY]- (b_18),
(d_0:AUTHOR{name: "DG Bae"}) -[:AUTHORS]-> (b_18),
(d_0) <-[:AUTHORED_BY]- (b_18),
(d_1:AUTHOR{name: "YS Gho"}) -[:AUTHORS]-> (b_18),
(d_1) <-[:AUTHORED_BY]- (b_18),
(d_2:AUTHOR{name: "WH Yoon"}) -[:AUTHORS]-> (b_18),
(d_2) <-[:AUTHORED_BY]- (b_18),
(d_3:AUTHOR{name: "CB Chae"}) -[:AUTHORS]-> (b_18),
(d_3) <-[:AUTHORED_BY]- (b_18),
(b_19:ARTICLE{title: "Biological effects of methylated amino acids.", id: None}),
(a_1) -[:REFERENCES]-> (b_19),
(a_1) <-[:REFERENCED_BY]- (b_19),
(d_0:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_19),
(d_0) <-[:AUTHORED_BY]- (b_19),
(d_1:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_19),
(d_1) <-[:AUTHORED_BY]- (b_19),
(d_2:AUTHOR{name: "L Trézl"}) -[:AUTHORS]-> (b_19),
(d_2) <-[:AUTHORED_BY]- (b_19),
(b_20:ARTICLE{title: "Biological significance of methylated derivatives of lysine and arginine.", id: 190512}),
(a_1) -[:REFERENCES]-> (b_20),
(a_1) <-[:REFERENCED_BY]- (b_20),
(d_0:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_20),
(d_0) <-[:AUTHORED_BY]- (b_20),
(d_1:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_20),
(d_1) <-[:AUTHORED_BY]- (b_20),
(d_2:AUTHOR{name: "K Lapis"}) -[:AUTHORS]-> (b_20),
(d_2) <-[:AUTHORED_BY]- (b_20),
(b_21:ARTICLE{title: "Formaldehyde generators and capturers as influencing factors of mitotic and apoptotic processes.", id: 10526976}),
(a_1) -[:REFERENCES]-> (b_21),
(a_1) <-[:REFERENCED_BY]- (b_21),
(d_0:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_21),
(d_0) <-[:AUTHORED_BY]- (b_21),
(d_1:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_21),
(d_1) <-[:AUTHORED_BY]- (b_21),
(d_2:AUTHOR{name: "L Trézl"}) -[:AUTHORS]-> (b_21),
(d_2) <-[:AUTHORED_BY]- (b_21),
(d_3:AUTHOR{name: "É Szöke"}) -[:AUTHORS]-> (b_21),
(d_3) <-[:AUTHORED_BY]- (b_21),
(d_4:AUTHOR{name: "I László"}) -[:AUTHORS]-> (b_21),
(d_4) <-[:AUTHORED_BY]- (b_21),
(d_5:AUTHOR{name: "GY Kátay"}) -[:AUTHORS]-> (b_21),
(d_5) <-[:AUTHORED_BY]- (b_21),
(d_6:AUTHOR{name: "ZS Király-Véghely"}) -[:AUTHORS]-> (b_21),
(d_6) <-[:AUTHORED_BY]- (b_21),
(b_22:ARTICLE{title: "Role of nitric oxide and peroxynitrite in bile salt-induced apoptosis. Relevance to colon carcinogenesis.", id: 10693173}),
(a_1) -[:REFERENCES]-> (b_22),
(a_1) <-[:REFERENCED_BY]- (b_22),
(d_0:AUTHOR{name: "D Washo-Stultz"}) -[:AUTHORS]-> (b_22),
(d_0) <-[:AUTHORED_BY]- (b_22),
(d_1:AUTHOR{name: "N Hoglen"}) -[:AUTHORS]-> (b_22),
(d_1) <-[:AUTHORED_BY]- (b_22),
(d_2:AUTHOR{name: "H Bernstein"}) -[:AUTHORS]-> (b_22),
(d_2) <-[:AUTHORED_BY]- (b_22),
(d_3:AUTHOR{name: "C Bernstein"}) -[:AUTHORS]-> (b_22),
(d_3) <-[:AUTHORED_BY]- (b_22),
(d_4:AUTHOR{name: "CM Payne"}) -[:AUTHORS]-> (b_22),
(d_4) <-[:AUTHORED_BY]- (b_22),
(b_23:ARTICLE{title: "Mechanisms of arginine-induced increase in cytosolic calcium concentration in the beta-cell line NIT-1.", id: 9112013}),
(a_1) -[:REFERENCES]-> (b_23),
(a_1) <-[:REFERENCED_BY]- (b_23),
(d_0:AUTHOR{name: "AJ Weinhaus"}) -[:AUTHORS]-> (b_23),
(d_0) <-[:AUTHORED_BY]- (b_23),
(d_1:AUTHOR{name: "P Poronnik"}) -[:AUTHORS]-> (b_23),
(d_1) <-[:AUTHORED_BY]- (b_23),
(d_2:AUTHOR{name: "BE Tuch"}) -[:AUTHORS]-> (b_23),
(d_2) <-[:AUTHORED_BY]- (b_23),
(d_3:AUTHOR{name: "DI Cook"}) -[:AUTHORS]-> (b_23),
(d_3) <-[:AUTHORED_BY]- (b_23),
(b_24:ARTICLE{title: "Intensified regression of colon cancer liver metastases in mice treated with irinotecan and the immunomodulator JBT 3002.", id: 10838661}),
(a_1) -[:REFERENCES]-> (b_24),
(a_1) <-[:REFERENCED_BY]- (b_24),
(d_0:AUTHOR{name: "H Shinohara"}) -[:AUTHORS]-> (b_24),
(d_0) <-[:AUTHORED_BY]- (b_24),
(d_1:AUTHOR{name: "CD Bucana"}) -[:AUTHORS]-> (b_24),
(d_1) <-[:AUTHORED_BY]- (b_24),
(d_2:AUTHOR{name: "JJ Killion"}) -[:AUTHORS]-> (b_24),
(d_2) <-[:AUTHORED_BY]- (b_24),
(d_3:AUTHOR{name: "IJ Fidler"}) -[:AUTHORS]-> (b_24),
(d_3) <-[:AUTHORED_BY]- (b_24),
(b_25:ARTICLE{title: "Nonlinear pharmacokinetics of L-N(G)-methyl-arginine in rats: characterization by an improved HPLC assay.", id: 10870097}),
(a_1) -[:REFERENCES]-> (b_25),
(a_1) <-[:REFERENCED_BY]- (b_25),
(d_0:AUTHOR{name: "TS Maurer"}) -[:AUTHORS]-> (b_25),
(d_0) <-[:AUTHORED_BY]- (b_25),
(d_1:AUTHOR{name: "Y Mishra"}) -[:AUTHORS]-> (b_25),
(d_1) <-[:AUTHORED_BY]- (b_25),
(d_2:AUTHOR{name: "HL Fung"}) -[:AUTHORS]-> (b_25),
(d_2) <-[:AUTHORED_BY]- (b_25),
(b_26:ARTICLE{title: "The hydrazine derivative aminoguanidine inhibits the reaction of tetrahydrofolic acid with hydroxymethylarginine biomolecule.", id: 10526969}),
(a_1) -[:REFERENCES]-> (b_26),
(a_1) <-[:REFERENCED_BY]- (b_26),
(d_0:AUTHOR{name: "L Hullan"}) -[:AUTHORS]-> (b_26),
(d_0) <-[:AUTHORED_BY]- (b_26),
(d_1:AUTHOR{name: "L Trézl"}) -[:AUTHORS]-> (b_26),
(d_1) <-[:AUTHORED_BY]- (b_26),
(d_2:AUTHOR{name: "T Szarvas"}) -[:AUTHORS]-> (b_26),
(d_2) <-[:AUTHORED_BY]- (b_26),
(d_3:AUTHOR{name: "A Csiba"}) -[:AUTHORS]-> (b_26),
(d_3) <-[:AUTHORED_BY]- (b_26),
(b_27:ARTICLE{title: "Formation of formaldehyde from S-adenosyl-L-(methyl-3H)methionine) during enzymic transmethylation of histamine.", id: 3792555}),
(a_1) -[:REFERENCES]-> (b_27),
(a_1) <-[:REFERENCED_BY]- (b_27),
(d_0:AUTHOR{name: "S Huszti"}) -[:AUTHORS]-> (b_27),
(d_0) <-[:AUTHORED_BY]- (b_27),
(d_1:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_27),
(d_1) <-[:AUTHORED_BY]- (b_27),
(b_28:ARTICLE{title: "Determination of endogenous formaldehyde in plants (fruits) bound to L-arginine and its relation to the folate cycle, photosynthesis and apoptosis.", id: 10526968}),
(a_1) -[:REFERENCES]-> (b_28),
(a_1) <-[:REFERENCED_BY]- (b_28),
(d_0:AUTHOR{name: "L Trézl"}) -[:AUTHORS]-> (b_28),
(d_0) <-[:AUTHORED_BY]- (b_28),
(d_1:AUTHOR{name: "L Hullán"}) -[:AUTHORS]-> (b_28),
(d_1) <-[:AUTHORED_BY]- (b_28),
(d_2:AUTHOR{name: "T Szarvas"}) -[:AUTHORS]-> (b_28),
(d_2) <-[:AUTHORED_BY]- (b_28),
(d_3:AUTHOR{name: "A Csiba"}) -[:AUTHORS]-> (b_28),
(d_3) <-[:AUTHORED_BY]- (b_28),
(d_4:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_28),
(d_4) <-[:AUTHORED_BY]- (b_28),
(b_29:ARTICLE{title: "Formaldehyde cycle and the natural formaldehyde generators and capturers.", id: 10526965}),
(a_1) -[:REFERENCES]-> (b_29),
(a_1) <-[:REFERENCED_BY]- (b_29),
(d_0:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_29),
(d_0) <-[:AUTHORED_BY]- (b_29),
(d_1:AUTHOR{name: "L Albert"}) -[:AUTHORS]-> (b_29),
(d_1) <-[:AUTHORED_BY]- (b_29),
(d_2:AUTHOR{name: "ZSL Németh"}) -[:AUTHORS]-> (b_29),
(d_2) <-[:AUTHORED_BY]- (b_29),
(d_3:AUTHOR{name: "GY Kátay"}) -[:AUTHORS]-> (b_29),
(d_3) <-[:AUTHORED_BY]- (b_29),
(d_4:AUTHOR{name: "ZS Király-Véghely"}) -[:AUTHORS]-> (b_29),
(d_4) <-[:AUTHORED_BY]- (b_29),
(d_5:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_29),
(d_5) <-[:AUTHORED_BY]- (b_29),
(b_30:ARTICLE{title: "Formaldehyde promotes and inhibits the proliferation of cultured tumour and endothelial cells.", id: 11380483}),
(a_1) -[:REFERENCES]-> (b_30),
(a_1) <-[:REFERENCED_BY]- (b_30),
(d_0:AUTHOR{name: "E Tyihák"}) -[:AUTHORS]-> (b_30),
(d_0) <-[:AUTHORED_BY]- (b_30),
(d_1:AUTHOR{name: "J Bocsi"}) -[:AUTHORS]-> (b_30),
(d_1) <-[:AUTHORED_BY]- (b_30),
(d_2:AUTHOR{name: "F Timár"}) -[:AUTHORS]-> (b_30),
(d_2) <-[:AUTHORED_BY]- (b_30),
(d_3:AUTHOR{name: "G Rácz"}) -[:AUTHORS]-> (b_30),
(d_3) <-[:AUTHORED_BY]- (b_30),
(d_4:AUTHOR{name: "B Szende"}) -[:AUTHORS]-> (b_30),
(d_4) <-[:AUTHORED_BY]- (b_30),
(b_31:ARTICLE{title: "Characterisation of cationic amino acid transporter and its gene expression in rat hepatic stellate cells in relation to nitric oxide production", id: None}),
(a_1) -[:REFERENCES]-> (b_31),
(a_1) <-[:REFERENCED_BY]- (b_31),
(d_0:AUTHOR{name: "K Ookawauchi"}) -[:AUTHORS]-> (b_31),
(d_0) <-[:AUTHORED_BY]- (b_31),
(d_1:AUTHOR{name: "T Saibara"}) -[:AUTHORS]-> (b_31),
(d_1) <-[:AUTHORED_BY]- (b_31),
(d_2:AUTHOR{name: "T Yoshikawa"}) -[:AUTHORS]-> (b_31),
(d_2) <-[:AUTHORED_BY]- (b_31),
(d_3:AUTHOR{name: "L Chun-Lin"}) -[:AUTHORS]-> (b_31),
(d_3) <-[:AUTHORED_BY]- (b_31),
(d_4:AUTHOR{name: "Y Hayashi"}) -[:AUTHORS]-> (b_31),
(d_4) <-[:AUTHORED_BY]- (b_31),
(d_5:AUTHOR{name: "M Hiroi"}) -[:AUTHORS]-> (b_31),
(d_5) <-[:AUTHORED_BY]- (b_31),
(d_6:AUTHOR{name: "H Enzan"}) -[:AUTHORS]-> (b_31),
(d_6) <-[:AUTHORED_BY]- (b_31),
(d_7:AUTHOR{name: "J Fukata"}) -[:AUTHORS]-> (b_31),
(d_7) <-[:AUTHORED_BY]- (b_31),
(d_8:AUTHOR{name: "S Onishi"}) -[:AUTHORS]-> (b_31),
(d_8) <-[:AUTHORED_BY]- (b_31),
(b_32:ARTICLE{title: "Combined analysis of germline polymorphisms of p53, GSTM1, GSTT1, CYP1A1 and CYP2E1: relation to the incidence rate of cervical carcinoma.", id: 10813720}),
(a_1) -[:REFERENCES]-> (b_32),
(a_1) <-[:REFERENCED_BY]- (b_32),
(d_0:AUTHOR{name: "JW Kirn"}) -[:AUTHORS]-> (b_32),
(d_0) <-[:AUTHORED_BY]- (b_32),
(d_1:AUTHOR{name: "CG Lee"}) -[:AUTHORS]-> (b_32),
(d_1) <-[:AUTHORED_BY]- (b_32),
(d_2:AUTHOR{name: "YG Park"}) -[:AUTHORS]-> (b_32),
(d_2) <-[:AUTHORED_BY]- (b_32),
(d_3:AUTHOR{name: "KS Kirn"}) -[:AUTHORS]-> (b_32),
(d_3) <-[:AUTHORED_BY]- (b_32),
(d_4:AUTHOR{name: "IK Kirn"}) -[:AUTHORS]-> (b_32),
(d_4) <-[:AUTHORED_BY]- (b_32),
(d_5:AUTHOR{name: "YW Sohn"}) -[:AUTHORS]-> (b_32),
(d_5) <-[:AUTHORED_BY]- (b_32),
(d_6:AUTHOR{name: "HK Min"}) -[:AUTHORS]-> (b_32),
(d_6) <-[:AUTHORED_BY]- (b_32),
(d_7:AUTHOR{name: "JM Lee"}) -[:AUTHORS]-> (b_32),
(d_7) <-[:AUTHORED_BY]- (b_32),
(d_8:AUTHOR{name: "SE Namkoong"}) -[:AUTHORS]-> (b_32),
(d_8) <-[:AUTHORED_BY]- (b_32),
(b_33:ARTICLE{title: "Correlation between human papilloma virus-associated cervical cancer and p53 codon 72 arginine/proline polymorphism.", id: 10647890}),
(a_1) -[:REFERENCES]-> (b_33),
(a_1) <-[:REFERENCED_BY]- (b_33),
(d_0:AUTHOR{name: "Tachezy R"}) -[:AUTHORS]-> (b_33),
(d_0) <-[:AUTHORED_BY]- (b_33),
(d_1:AUTHOR{name: "I Mikyskova"}) -[:AUTHORS]-> (b_33),
(d_1) <-[:AUTHORED_BY]- (b_33),
(d_2:AUTHOR{name: "M Salakova"}) -[:AUTHORS]-> (b_33),
(d_2) <-[:AUTHORED_BY]- (b_33),
(d_3:AUTHOR{name: "M Van Ranst"}) -[:AUTHORS]-> (b_33),
(d_3) <-[:AUTHORED_BY]- (b_33),
(c_0:AUTHOR{name: "Bela Szende"}) -[:AUTHORS]-> (a_1),
(c_0) <-[:AUTHORED_BY]- (a_1),
(c_1:AUTHOR{name: "Erno Tyihák"}) -[:AUTHORS]-> (a_1),
(c_1) <-[:AUTHORED_BY]- (a_1),
(c_2:AUTHOR{name: "Lajos Trézl"}) -[:AUTHORS]-> (a_1),
(c_2) <-[:AUTHORED_BY]- (a_1),

(a_2:ARTICLE{title: "Effect of various types of milk on salivary pH among children: a pilot randomized controlled crossover trial", id: 10500012}),
(b_0:ARTICLE{title: "Health-related aspects of milk proteins", id: 27980594}),
(a_2) -[:REFERENCES]-> (b_0),
(a_2) <-[:REFERENCED_BY]- (b_0),
(d_0:AUTHOR{name: "SH Davoodi"}) -[:AUTHORS]-> (b_0),
(d_0) <-[:AUTHORED_BY]- (b_0),
(d_1:AUTHOR{name: "R Shahbazi"}) -[:AUTHORS]-> (b_0),
(d_1) <-[:AUTHORED_BY]- (b_0),
(d_2:AUTHOR{name: "S Esmaeili"}) -[:AUTHORS]-> (b_0),
(d_2) <-[:AUTHORED_BY]- (b_0),
(d_3:AUTHOR{name: "S Sohrabvandi"}) -[:AUTHORS]-> (b_0),
(d_3) <-[:AUTHORED_BY]- (b_0),
(d_4:AUTHOR{name: "A Mortazavian"}) -[:AUTHORS]-> (b_0),
(d_4) <-[:AUTHORED_BY]- (b_0),
(d_5:AUTHOR{name: "S Jazayeri"}) -[:AUTHORS]-> (b_0),
(d_5) <-[:AUTHORED_BY]- (b_0),
(b_1:ARTICLE{title: "Impact of dairy products and plant-based alternatives on dental health: food matrix effects", id: 36986199}),
(a_2) -[:REFERENCES]-> (b_1),
(a_2) <-[:REFERENCED_BY]- (b_1),
(d_0:AUTHOR{name: "B Shkembi"}) -[:AUTHORS]-> (b_1),
(d_0) <-[:AUTHORED_BY]- (b_1),
(d_1:AUTHOR{name: "T Huppertz"}) -[:AUTHORS]-> (b_1),
(d_1) <-[:AUTHORED_BY]- (b_1),
(b_2:ARTICLE{title: "Milk and dairy products and their nutritional contribution to the average polish diet", id: 31374893}),
(a_2) -[:REFERENCES]-> (b_2),
(a_2) <-[:REFERENCED_BY]- (b_2),
(d_0:AUTHOR{name: "H Górska-Warsewicz"}) -[:AUTHORS]-> (b_2),
(d_0) <-[:AUTHORED_BY]- (b_2),
(d_1:AUTHOR{name: "K Rejman"}) -[:AUTHORS]-> (b_2),
(d_1) <-[:AUTHORED_BY]- (b_2),
(d_2:AUTHOR{name: "W Laskowski"}) -[:AUTHORS]-> (b_2),
(d_2) <-[:AUTHORED_BY]- (b_2),
(d_3:AUTHOR{name: "M Czeczotko"}) -[:AUTHORS]-> (b_2),
(d_3) <-[:AUTHORED_BY]- (b_2),
(b_3:ARTICLE{title: "Cow’s milk in human nutrition and the emergence of plant-based milk alternatives", id: 36613315}),
(a_2) -[:REFERENCES]-> (b_3),
(a_2) <-[:REFERENCED_BY]- (b_3),
(d_0:AUTHOR{name: "IC Antunes"}) -[:AUTHORS]-> (b_3),
(d_0) <-[:AUTHORED_BY]- (b_3),
(d_1:AUTHOR{name: "R Bexiga"}) -[:AUTHORS]-> (b_3),
(d_1) <-[:AUTHORED_BY]- (b_3),
(d_2:AUTHOR{name: "C Pinto"}) -[:AUTHORS]-> (b_3),
(d_2) <-[:AUTHORED_BY]- (b_3),
(d_3:AUTHOR{name: "LC Roseiro"}) -[:AUTHORS]-> (b_3),
(d_3) <-[:AUTHORED_BY]- (b_3),
(d_4:AUTHOR{name: "MA Quaresma"}) -[:AUTHORS]-> (b_3),
(d_4) <-[:AUTHORED_BY]- (b_3),
(b_4:ARTICLE{title: "The effects of a high-protein dairy milk beverage with or without progressive resistance training on fat-free mass, skeletal muscle strength and power, and functional performance in healthy active older adults: a 12-week randomized controlled trial", id: 33816540}),
(a_2) -[:REFERENCES]-> (b_4),
(a_2) <-[:REFERENCED_BY]- (b_4),
(d_0:AUTHOR{name: "Z Huschtscha"}) -[:AUTHORS]-> (b_4),
(d_0) <-[:AUTHORED_BY]- (b_4),
(d_1:AUTHOR{name: "A Parr"}) -[:AUTHORS]-> (b_4),
(d_1) <-[:AUTHORED_BY]- (b_4),
(d_2:AUTHOR{name: "J Porter"}) -[:AUTHORS]-> (b_4),
(d_2) <-[:AUTHORED_BY]- (b_4),
(d_3:AUTHOR{name: "RJ Costa"}) -[:AUTHORS]-> (b_4),
(d_3) <-[:AUTHORED_BY]- (b_4),
(b_5:ARTICLE{title: "Protein intake and oral health in older adults—a narrative review", id: 36364741}),
(a_2) -[:REFERENCES]-> (b_5),
(a_2) <-[:REFERENCED_BY]- (b_5),
(d_0:AUTHOR{name: "TN Jayasinghe"}) -[:AUTHORS]-> (b_5),
(d_0) <-[:AUTHORED_BY]- (b_5),
(d_1:AUTHOR{name: "S Harrass"}) -[:AUTHORS]-> (b_5),
(d_1) <-[:AUTHORED_BY]- (b_5),
(d_2:AUTHOR{name: "S Erdrich"}) -[:AUTHORS]-> (b_5),
(d_2) <-[:AUTHORED_BY]- (b_5),
(d_3:AUTHOR{name: "S King"}) -[:AUTHORS]-> (b_5),
(d_3) <-[:AUTHORED_BY]- (b_5),
(d_4:AUTHOR{name: "J Eberhard"}) -[:AUTHORS]-> (b_5),
(d_4) <-[:AUTHORED_BY]- (b_5),
(b_6:ARTICLE{title: "Effect of whole milk compared with skimmed milk on fasting blood lipids in healthy adults: a 3-week randomized crossover study", id: 29229955}),
(a_2) -[:REFERENCES]-> (b_6),
(a_2) <-[:REFERENCED_BY]- (b_6),
(d_0:AUTHOR{name: "S Engel"}) -[:AUTHORS]-> (b_6),
(d_0) <-[:AUTHORED_BY]- (b_6),
(d_1:AUTHOR{name: "M Elhauge"}) -[:AUTHORS]-> (b_6),
(d_1) <-[:AUTHORED_BY]- (b_6),
(d_2:AUTHOR{name: "T Tholstrup"}) -[:AUTHORS]-> (b_6),
(d_2) <-[:AUTHORED_BY]- (b_6),
(b_7:ARTICLE{title: "Whole milk compared with reduced-fat milk and childhood overweight: a systematic review and meta-analysis", id: 31851302}),
(a_2) -[:REFERENCES]-> (b_7),
(a_2) <-[:REFERENCED_BY]- (b_7),
(d_0:AUTHOR{name: "SM Vanderhout"}) -[:AUTHORS]-> (b_7),
(d_0) <-[:AUTHORED_BY]- (b_7),
(d_1:AUTHOR{name: "M Aglipay"}) -[:AUTHORS]-> (b_7),
(d_1) <-[:AUTHORED_BY]- (b_7),
(d_2:AUTHOR{name: "N Torabi"}) -[:AUTHORS]-> (b_7),
(d_2) <-[:AUTHORED_BY]- (b_7),
(d_3:AUTHOR{name: "P Jüni"}) -[:AUTHORS]-> (b_7),
(d_3) <-[:AUTHORED_BY]- (b_7),
(d_4:AUTHOR{name: "BR da Costa"}) -[:AUTHORS]-> (b_7),
(d_4) <-[:AUTHORED_BY]- (b_7),
(d_5:AUTHOR{name: "CS Birken"}) -[:AUTHORS]-> (b_7),
(d_5) <-[:AUTHORED_BY]- (b_7),
(b_8:ARTICLE{title: "Review of infant feeding: key features of breast milk and infant formula", id: 27187450}),
(a_2) -[:REFERENCES]-> (b_8),
(a_2) <-[:REFERENCED_BY]- (b_8),
(d_0:AUTHOR{name: "CR Martin"}) -[:AUTHORS]-> (b_8),
(d_0) <-[:AUTHORED_BY]- (b_8),
(d_1:AUTHOR{name: "PR Ling"}) -[:AUTHORS]-> (b_8),
(d_1) <-[:AUTHORED_BY]- (b_8),
(d_2:AUTHOR{name: "GL Blackburn"}) -[:AUTHORS]-> (b_8),
(d_2) <-[:AUTHORED_BY]- (b_8),
(b_9:ARTICLE{title: "Buse K. Characterization of protein and fat in dairy feeds and implications on digestibility and milk composition. Theses and Dissertations in Animal Science. 2020:1–140.", id: None}),
(a_2) -[:REFERENCES]-> (b_9),
(a_2) <-[:REFERENCED_BY]- (b_9),
(b_10:ARTICLE{title: "Biochemistry of fat soluble vitamins, sources, biochemical functions and toxicity", id: None}),
(a_2) -[:REFERENCES]-> (b_10),
(a_2) <-[:REFERENCED_BY]- (b_10),
(d_0:AUTHOR{name: "H Rafeeq"}) -[:AUTHORS]-> (b_10),
(d_0) <-[:AUTHORED_BY]- (b_10),
(d_1:AUTHOR{name: "S Ahmad"}) -[:AUTHORS]-> (b_10),
(d_1) <-[:AUTHORED_BY]- (b_10),
(d_2:AUTHOR{name: "MB Tareen"}) -[:AUTHORS]-> (b_10),
(d_2) <-[:AUTHORED_BY]- (b_10),
(d_3:AUTHOR{name: "KA Shahzad"}) -[:AUTHORS]-> (b_10),
(d_3) <-[:AUTHORED_BY]- (b_10),
(d_4:AUTHOR{name: "A Bashir"}) -[:AUTHORS]-> (b_10),
(d_4) <-[:AUTHORED_BY]- (b_10),
(d_5:AUTHOR{name: "R Jabeen"}) -[:AUTHORS]-> (b_10),
(d_5) <-[:AUTHORED_BY]- (b_10),
(b_11:ARTICLE{title: "Variations in sugar content of flavored milks and yogurts: a cross-sectional study across 3 countries", id: 31187086}),
(a_2) -[:REFERENCES]-> (b_11),
(a_2) <-[:REFERENCED_BY]- (b_11),
(d_0:AUTHOR{name: "DH Coyle"}) -[:AUTHORS]-> (b_11),
(d_0) <-[:AUTHORED_BY]- (b_11),
(d_1:AUTHOR{name: "R Ndanuko"}) -[:AUTHORS]-> (b_11),
(d_1) <-[:AUTHORED_BY]- (b_11),
(d_2:AUTHOR{name: "S Singh"}) -[:AUTHORS]-> (b_11),
(d_2) <-[:AUTHORED_BY]- (b_11),
(d_3:AUTHOR{name: "P Huang"}) -[:AUTHORS]-> (b_11),
(d_3) <-[:AUTHORED_BY]- (b_11),
(d_4:AUTHOR{name: "JH Wu"}) -[:AUTHORS]-> (b_11),
(d_4) <-[:AUTHORED_BY]- (b_11),
(b_12:ARTICLE{title: "Effect of flavored milk vs plain milk on total milk intake and nutrient provision in children", id: 26534904}),
(a_2) -[:REFERENCES]-> (b_12),
(a_2) <-[:REFERENCED_BY]- (b_12),
(d_0:AUTHOR{name: "F Fayet-Moore"}) -[:AUTHORS]-> (b_12),
(d_0) <-[:AUTHORED_BY]- (b_12),
(b_13:ARTICLE{title: "Evaluating the cariogenic potential of flavored milk: an experimental study using rat model", id: 25876949}),
(a_2) -[:REFERENCES]-> (b_13),
(a_2) <-[:REFERENCED_BY]- (b_13),
(d_0:AUTHOR{name: "A Al-Jobair"}) -[:AUTHORS]-> (b_13),
(d_0) <-[:AUTHORED_BY]- (b_13),
(d_1:AUTHOR{name: "R Khounganian"}) -[:AUTHORS]-> (b_13),
(d_1) <-[:AUTHORED_BY]- (b_13),
(b_14:ARTICLE{title: "The role of natural salivary defences in maintaining a healthy oral microbiota", id: 30696553}),
(a_2) -[:REFERENCES]-> (b_14),
(a_2) <-[:REFERENCED_BY]- (b_14),
(d_0:AUTHOR{name: "AM Pedersen"}) -[:AUTHORS]-> (b_14),
(d_0) <-[:AUTHORED_BY]- (b_14),
(d_1:AUTHOR{name: "D Belstrøm"}) -[:AUTHORS]-> (b_14),
(d_1) <-[:AUTHORED_BY]- (b_14),
(b_15:ARTICLE{title: "Saliva between normal and pathological. Important factors in determining systemic and oral health", id: 20112475}),
(a_2) -[:REFERENCES]-> (b_15),
(a_2) <-[:REFERENCED_BY]- (b_15),
(d_0:AUTHOR{name: "G Iorgulescu"}) -[:AUTHORS]-> (b_15),
(d_0) <-[:AUTHORED_BY]- (b_15),
(b_16:ARTICLE{title: "Salivary pH: a diagnostic biomarker", id: 24174725}),
(a_2) -[:REFERENCES]-> (b_16),
(a_2) <-[:REFERENCED_BY]- (b_16),
(d_0:AUTHOR{name: "S Baliga"}) -[:AUTHORS]-> (b_16),
(d_0) <-[:AUTHORED_BY]- (b_16),
(d_1:AUTHOR{name: "S Muglikar"}) -[:AUTHORS]-> (b_16),
(d_1) <-[:AUTHORED_BY]- (b_16),
(d_2:AUTHOR{name: "R Kale"}) -[:AUTHORS]-> (b_16),
(d_2) <-[:AUTHORED_BY]- (b_16),
(b_17:ARTICLE{title: "Opportunities for caries prevention using an ion-releasing coating material: a randomised clinical study", id: 32888115}),
(a_2) -[:REFERENCES]-> (b_17),
(a_2) <-[:REFERENCED_BY]- (b_17),
(d_0:AUTHOR{name: "U Örtengren"}) -[:AUTHORS]-> (b_17),
(d_0) <-[:AUTHORED_BY]- (b_17),
(d_1:AUTHOR{name: "A Lehrkinder"}) -[:AUTHORS]-> (b_17),
(d_1) <-[:AUTHORED_BY]- (b_17),
(d_2:AUTHOR{name: "A Safarloo"}) -[:AUTHORS]-> (b_17),
(d_2) <-[:AUTHORED_BY]- (b_17),
(d_3:AUTHOR{name: "J Axelsson"}) -[:AUTHORS]-> (b_17),
(d_3) <-[:AUTHORED_BY]- (b_17),
(d_4:AUTHOR{name: "P Lingström"}) -[:AUTHORS]-> (b_17),
(d_4) <-[:AUTHORED_BY]- (b_17),
(b_18:ARTICLE{title: "Estimation of salivary flow rate, pH, buffer capacity, calcium, total protein content and total antioxidant capacity in relation to dental caries severity, age and gender", id: 25821379}),
(a_2) -[:REFERENCES]-> (b_18),
(a_2) <-[:REFERENCED_BY]- (b_18),
(d_0:AUTHOR{name: "P Pandey"}) -[:AUTHORS]-> (b_18),
(d_0) <-[:AUTHORED_BY]- (b_18),
(d_1:AUTHOR{name: "NV Reddy"}) -[:AUTHORS]-> (b_18),
(d_1) <-[:AUTHORED_BY]- (b_18),
(d_2:AUTHOR{name: "VA Rao"}) -[:AUTHORS]-> (b_18),
(d_2) <-[:AUTHORED_BY]- (b_18),
(d_3:AUTHOR{name: "A Saxena"}) -[:AUTHORS]-> (b_18),
(d_3) <-[:AUTHORED_BY]- (b_18),
(d_4:AUTHOR{name: "CP Chaudhary"}) -[:AUTHORS]-> (b_18),
(d_4) <-[:AUTHORED_BY]- (b_18),
(b_19:ARTICLE{title: "Human experimentation. Code of ethics of the world medical association. Declaration of Helsinki", id: 14150898}),
(a_2) -[:REFERENCES]-> (b_19),
(a_2) <-[:REFERENCED_BY]- (b_19),
(d_0:AUTHOR{name: "R PP"}) -[:AUTHORS]-> (b_19),
(d_0) <-[:AUTHORED_BY]- (b_19),
(b_20:ARTICLE{title: "The CONSORT statement", id: 30930716}),
(a_2) -[:REFERENCES]-> (b_20),
(a_2) <-[:REFERENCED_BY]- (b_20),
(d_0:AUTHOR{name: "S Cuschieri"}) -[:AUTHORS]-> (b_20),
(d_0) <-[:AUTHORED_BY]- (b_20),
(b_21:ARTICLE{title: "Oral hygiene index in early childhood caries, before and after topicalfluoride treatment", id: 29531609}),
(a_2) -[:REFERENCES]-> (b_21),
(a_2) <-[:REFERENCED_BY]- (b_21),
(d_0:AUTHOR{name: "OR Okoceva-Ivanovska"}) -[:AUTHORS]-> (b_21),
(d_0) <-[:AUTHORED_BY]- (b_21),
(d_1:AUTHOR{name: "O Sarakinova"}) -[:AUTHORS]-> (b_21),
(d_1) <-[:AUTHORED_BY]- (b_21),
(d_2:AUTHOR{name: "E Zabokova-Bilbilova"}) -[:AUTHORS]-> (b_21),
(d_2) <-[:AUTHORED_BY]- (b_21),
(d_3:AUTHOR{name: "AN Mijoska"}) -[:AUTHORS]-> (b_21),
(d_3) <-[:AUTHORED_BY]- (b_21),
(d_4:AUTHOR{name: "N Stav-reva"}) -[:AUTHORS]-> (b_21),
(d_4) <-[:AUTHORED_BY]- (b_21),
(b_22:ARTICLE{title: "Effects of carbonated beverage consumption on oral pH and bacterial proliferation in adolescents: a randomized crossover clinical trial", id: 36362931}),
(a_2) -[:REFERENCES]-> (b_22),
(a_2) <-[:REFERENCED_BY]- (b_22),
(d_0:AUTHOR{name: "GC Barajas-Torres"}) -[:AUTHORS]-> (b_22),
(d_0) <-[:AUTHORED_BY]- (b_22),
(d_1:AUTHOR{name: "M Klünder-Klünder"}) -[:AUTHORS]-> (b_22),
(d_1) <-[:AUTHORED_BY]- (b_22),
(d_2:AUTHOR{name: "J Garduño-Espinosa"}) -[:AUTHORS]-> (b_22),
(d_2) <-[:AUTHORED_BY]- (b_22),
(d_3:AUTHOR{name: "I Parra-Ortega"}) -[:AUTHORS]-> (b_22),
(d_3) <-[:AUTHORED_BY]- (b_22),
(d_4:AUTHOR{name: "MI Franco-Hernández"}) -[:AUTHORS]-> (b_22),
(d_4) <-[:AUTHORED_BY]- (b_22),
(d_5:AUTHOR{name: "AL Miranda-Lora"}) -[:AUTHORS]-> (b_22),
(d_5) <-[:AUTHORED_BY]- (b_22),
(b_23:ARTICLE{title: "Evaluation of salivary parameters and Streptococcus’ Mutans count in children with cerebral palsy in Egypt: a case control study", id: 36123671}),
(a_2) -[:REFERENCES]-> (b_23),
(a_2) <-[:REFERENCED_BY]- (b_23),
(d_0:AUTHOR{name: "SM Quritum"}) -[:AUTHORS]-> (b_23),
(d_0) <-[:AUTHORED_BY]- (b_23),
(d_1:AUTHOR{name: "AM Ali"}) -[:AUTHORS]-> (b_23),
(d_1) <-[:AUTHORED_BY]- (b_23),
(d_2:AUTHOR{name: "MM Raouf"}) -[:AUTHORS]-> (b_23),
(d_2) <-[:AUTHORED_BY]- (b_23),
(d_3:AUTHOR{name: "TE Omar"}) -[:AUTHORS]-> (b_23),
(d_3) <-[:AUTHORED_BY]- (b_23),
(d_4:AUTHOR{name: "KM Dowidar"}) -[:AUTHORS]-> (b_23),
(d_4) <-[:AUTHORED_BY]- (b_23),
(b_24:ARTICLE{title: "Remineralization of teeth with casein phosphopeptide-amorphous calcium phosphate: analysis of salivary pH and the rate of salivary flow", id: 37041136}),
(a_2) -[:REFERENCES]-> (b_24),
(a_2) <-[:REFERENCED_BY]- (b_24),
(d_0:AUTHOR{name: "L Alkarad"}) -[:AUTHORS]-> (b_24),
(d_0) <-[:AUTHORED_BY]- (b_24),
(d_1:AUTHOR{name: "M Alkhouli"}) -[:AUTHORS]-> (b_24),
(d_1) <-[:AUTHORED_BY]- (b_24),
(d_2:AUTHOR{name: "M Dashash"}) -[:AUTHORS]-> (b_24),
(d_2) <-[:AUTHORED_BY]- (b_24),
(b_25:ARTICLE{title: "Sugars and dental caries: evidence for setting a recommended threshold for intake", id: 26773022}),
(a_2) -[:REFERENCES]-> (b_25),
(a_2) <-[:REFERENCED_BY]- (b_25),
(d_0:AUTHOR{name: "P Moynihan"}) -[:AUTHORS]-> (b_25),
(d_0) <-[:AUTHORED_BY]- (b_25),
(b_26:ARTICLE{title: "Salivary biomarkers: novel noninvasive tools to diagnose chronic inflammation", id: 37386003}),
(a_2) -[:REFERENCES]-> (b_26),
(a_2) <-[:REFERENCED_BY]- (b_26),
(d_0:AUTHOR{name: "P Dongiovanni"}) -[:AUTHORS]-> (b_26),
(d_0) <-[:AUTHORED_BY]- (b_26),
(d_1:AUTHOR{name: "M Meroni"}) -[:AUTHORS]-> (b_26),
(d_1) <-[:AUTHORED_BY]- (b_26),
(d_2:AUTHOR{name: "S Casati"}) -[:AUTHORS]-> (b_26),
(d_2) <-[:AUTHORED_BY]- (b_26),
(d_3:AUTHOR{name: "R Goldoni"}) -[:AUTHORS]-> (b_26),
(d_3) <-[:AUTHORED_BY]- (b_26),
(d_4:AUTHOR{name: "DV Thomaz"}) -[:AUTHORS]-> (b_26),
(d_4) <-[:AUTHORED_BY]- (b_26),
(d_5:AUTHOR{name: "NS Kehr"}) -[:AUTHORS]-> (b_26),
(d_5) <-[:AUTHORED_BY]- (b_26),
(b_27:ARTICLE{title: "Correlation of salivary pH, incidence of dental caries and periodontal status in diabetes mellitus patients: a cross-sectional study", id: 27134992}),
(a_2) -[:REFERENCES]-> (b_27),
(a_2) <-[:REFERENCED_BY]- (b_27),
(d_0:AUTHOR{name: "C Seethalakshmi"}) -[:AUTHORS]-> (b_27),
(d_0) <-[:AUTHORED_BY]- (b_27),
(d_1:AUTHOR{name: "RJ Reddy"}) -[:AUTHORS]-> (b_27),
(d_1) <-[:AUTHORED_BY]- (b_27),
(d_2:AUTHOR{name: "N Asifa"}) -[:AUTHORS]-> (b_27),
(d_2) <-[:AUTHORED_BY]- (b_27),
(d_3:AUTHOR{name: "S Prabhu"}) -[:AUTHORS]-> (b_27),
(d_3) <-[:AUTHORED_BY]- (b_27),
(b_28:ARTICLE{title: "Evaluation of changes in salivary pH after intake of different eatables and beverages in children at different time intervals", id: 30131637}),
(a_2) -[:REFERENCES]-> (b_28),
(a_2) <-[:REFERENCED_BY]- (b_28),
(d_0:AUTHOR{name: "A Pachori"}) -[:AUTHORS]-> (b_28),
(d_0) <-[:AUTHORED_BY]- (b_28),
(d_1:AUTHOR{name: "H Kambalimath"}) -[:AUTHORS]-> (b_28),
(d_1) <-[:AUTHORED_BY]- (b_28),
(d_2:AUTHOR{name: "S Maran"}) -[:AUTHORS]-> (b_28),
(d_2) <-[:AUTHORED_BY]- (b_28),
(d_3:AUTHOR{name: "B Niranjan"}) -[:AUTHORS]-> (b_28),
(d_3) <-[:AUTHORED_BY]- (b_28),
(d_4:AUTHOR{name: "G Bhambhani"}) -[:AUTHORS]-> (b_28),
(d_4) <-[:AUTHORED_BY]- (b_28),
(d_5:AUTHOR{name: "G Malhotra"}) -[:AUTHORS]-> (b_28),
(d_5) <-[:AUTHORED_BY]- (b_28),
(b_29:ARTICLE{title: "Clinical usefulness of pH papers in the measurement of salivary pH", id: None}),
(a_2) -[:REFERENCES]-> (b_29),
(a_2) <-[:REFERENCED_BY]- (b_29),
(d_0:AUTHOR{name: "CW Song"}) -[:AUTHORS]-> (b_29),
(d_0) <-[:AUTHORED_BY]- (b_29),
(d_1:AUTHOR{name: "HK Kim"}) -[:AUTHORS]-> (b_29),
(d_1) <-[:AUTHORED_BY]- (b_29),
(d_2:AUTHOR{name: "ME Kim"}) -[:AUTHORS]-> (b_29),
(d_2) <-[:AUTHORED_BY]- (b_29),
(b_30:ARTICLE{title: "Impact of the removal of chocolate milk from school milk programs for children in Saskatoon, Canada", id: 25585706}),
(a_2) -[:REFERENCES]-> (b_30),
(a_2) <-[:REFERENCED_BY]- (b_30),
(d_0:AUTHOR{name: "C Henry"}) -[:AUTHORS]-> (b_30),
(d_0) <-[:AUTHORED_BY]- (b_30),
(d_1:AUTHOR{name: "SJ Whiting"}) -[:AUTHORS]-> (b_30),
(d_1) <-[:AUTHORED_BY]- (b_30),
(d_2:AUTHOR{name: "T Phillips"}) -[:AUTHORS]-> (b_30),
(d_2) <-[:AUTHORED_BY]- (b_30),
(d_3:AUTHOR{name: "SL Finch"}) -[:AUTHORS]-> (b_30),
(d_3) <-[:AUTHORED_BY]- (b_30),
(d_4:AUTHOR{name: "GA Zello"}) -[:AUTHORS]-> (b_30),
(d_4) <-[:AUTHORED_BY]- (b_30),
(d_5:AUTHOR{name: "H Vatanparast"}) -[:AUTHORS]-> (b_30),
(d_5) <-[:AUTHORED_BY]- (b_30),
(b_31:ARTICLE{title: "The adsorption of skimmed milk and full-fat milk solution on the surface of natural teeth", id: None}),
(a_2) -[:REFERENCES]-> (b_31),
(a_2) <-[:REFERENCED_BY]- (b_31),
(d_0:AUTHOR{name: "RJ Timimi"}) -[:AUTHORS]-> (b_31),
(d_0) <-[:AUTHORED_BY]- (b_31),
(d_1:AUTHOR{name: "HS Jassim"}) -[:AUTHORS]-> (b_31),
(d_1) <-[:AUTHORED_BY]- (b_31),
(d_2:AUTHOR{name: "ST Abd"}) -[:AUTHORS]-> (b_31),
(d_2) <-[:AUTHORED_BY]- (b_31),
(b_32:ARTICLE{title: "Salivary protein concentration, flow rate, buffer capacity and pH estimation: a comparative study among young and elderly subjects, both normal and with gingivitis and periodontitis", id: 23633771}),
(a_2) -[:REFERENCES]-> (b_32),
(a_2) <-[:REFERENCED_BY]- (b_32),
(d_0:AUTHOR{name: "M Shaila"}) -[:AUTHORS]-> (b_32),
(d_0) <-[:AUTHORED_BY]- (b_32),
(d_1:AUTHOR{name: "GP Pai"}) -[:AUTHORS]-> (b_32),
(d_1) <-[:AUTHORED_BY]- (b_32),
(d_2:AUTHOR{name: "P Shetty"}) -[:AUTHORS]-> (b_32),
(d_2) <-[:AUTHORED_BY]- (b_32),
(b_33:ARTICLE{title: "Differences in saliva pH before and after drinking packed cow’s milk in children aged 6–12 years", id: None}),
(a_2) -[:REFERENCES]-> (b_33),
(a_2) <-[:REFERENCED_BY]- (b_33),
(d_0:AUTHOR{name: "S Sulastri"}) -[:AUTHORS]-> (b_33),
(d_0) <-[:AUTHORED_BY]- (b_33),
(d_1:AUTHOR{name: "H Sulistyani"}) -[:AUTHORS]-> (b_33),
(d_1) <-[:AUTHORED_BY]- (b_33),
(b_34:ARTICLE{title: "Perbedaan pH saliva sebelum dan sesudah mengkonsumsi susu formula dengan susu UHT (studi pada anak di Panti Asuhan Nirmala Banda Aceh)", id: None}),
(a_2) -[:REFERENCES]-> (b_34),
(a_2) <-[:REFERENCED_BY]- (b_34),
(d_0:AUTHOR{name: "CN Savira"}) -[:AUTHORS]-> (b_34),
(d_0) <-[:AUTHORED_BY]- (b_34),
(d_1:AUTHOR{name: "RF Hakim"}) -[:AUTHORS]-> (b_34),
(d_1) <-[:AUTHORED_BY]- (b_34),
(d_2:AUTHOR{name: "S Sungkar"}) -[:AUTHORS]-> (b_34),
(d_2) <-[:AUTHORED_BY]- (b_34),
(b_35:ARTICLE{title: "Azrak B, Willershausen B, Meyer N, Callaway A. Course of changes in salivary pH-values after intake of different beverages in young children. Oral Health Prev Dent. 2008;6:159–64.", id: None}),
(a_2) -[:REFERENCES]-> (b_35),
(a_2) <-[:REFERENCED_BY]- (b_35),
(b_36:ARTICLE{title: "Evaluating the effect of probiotic containing milk on salivary mutans streptococci levels", id: 23342560}),
(a_2) -[:REFERENCES]-> (b_36),
(a_2) <-[:REFERENCED_BY]- (b_36),
(d_0:AUTHOR{name: "A Juneja"}) -[:AUTHORS]-> (b_36),
(d_0) <-[:AUTHORED_BY]- (b_36),
(d_1:AUTHOR{name: "A Kakade"}) -[:AUTHORS]-> (b_36),
(d_1) <-[:AUTHORED_BY]- (b_36),
(b_37:ARTICLE{title: "Perbedaan pH Saliva Setelah Mengonsumsi Susu Sapi Murni dan Susu Sapi Bubuk", id: None}),
(a_2) -[:REFERENCES]-> (b_37),
(a_2) <-[:REFERENCED_BY]- (b_37),
(d_0:AUTHOR{name: "IT Seralurin"}) -[:AUTHORS]-> (b_37),
(d_0) <-[:AUTHORED_BY]- (b_37),
(d_1:AUTHOR{name: "VN Wowor"}) -[:AUTHORS]-> (b_37),
(d_1) <-[:AUTHORED_BY]- (b_37),
(d_2:AUTHOR{name: "SH Ticoalu"}) -[:AUTHORS]-> (b_37),
(d_2) <-[:AUTHORED_BY]- (b_37),
(b_38:ARTICLE{title: "Effects of different beverages on salivary ph and time taken by saliva to regain normal pH among teenagers", id: None}),
(a_2) -[:REFERENCES]-> (b_38),
(a_2) <-[:REFERENCED_BY]- (b_38),
(d_0:AUTHOR{name: "H Hirani"}) -[:AUTHORS]-> (b_38),
(d_0) <-[:AUTHORED_BY]- (b_38),
(d_1:AUTHOR{name: "N Iqbal"}) -[:AUTHORS]-> (b_38),
(d_1) <-[:AUTHORED_BY]- (b_38),
(d_2:AUTHOR{name: "AN Bijarani"}) -[:AUTHORS]-> (b_38),
(d_2) <-[:AUTHORED_BY]- (b_38),
(d_3:AUTHOR{name: "UP Hashmi"}) -[:AUTHORS]-> (b_38),
(d_3) <-[:AUTHORED_BY]- (b_38),
(d_4:AUTHOR{name: "S Khurram"}) -[:AUTHORS]-> (b_38),
(d_4) <-[:AUTHORED_BY]- (b_38),
(d_5:AUTHOR{name: "NJ Baig"}) -[:AUTHORS]-> (b_38),
(d_5) <-[:AUTHORED_BY]- (b_38),
(b_39:ARTICLE{title: "Acidogenic potential of plain milk, milk with sugar, milk with cornflakes and milk cornflakes with sugar: a comparative study", id: 27843253}),
(a_2) -[:REFERENCES]-> (b_39),
(a_2) <-[:REFERENCED_BY]- (b_39),
(d_0:AUTHOR{name: "SS Bhat"}) -[:AUTHORS]-> (b_39),
(d_0) <-[:AUTHORED_BY]- (b_39),
(d_1:AUTHOR{name: "SK Hegde"}) -[:AUTHORS]-> (b_39),
(d_1) <-[:AUTHORED_BY]- (b_39),
(d_2:AUTHOR{name: "VS Bhat"}) -[:AUTHORS]-> (b_39),
(d_2) <-[:AUTHORED_BY]- (b_39),
(d_3:AUTHOR{name: "KM Ramya"}) -[:AUTHORS]-> (b_39),
(d_3) <-[:AUTHORED_BY]- (b_39),
(d_4:AUTHOR{name: "PS Jodalli"}) -[:AUTHORS]-> (b_39),
(d_4) <-[:AUTHORED_BY]- (b_39),
(b_40:ARTICLE{title: "Little color, little flavor of different kinds of commercially available flavored milk and their consumption effect on salivary pH value in children: an in vivo study", id: 34434020}),
(a_2) -[:REFERENCES]-> (b_40),
(a_2) <-[:REFERENCED_BY]- (b_40),
(d_0:AUTHOR{name: "S Navit"}) -[:AUTHORS]-> (b_40),
(d_0) <-[:AUTHORED_BY]- (b_40),
(d_1:AUTHOR{name: "S Agarwal"}) -[:AUTHORS]-> (b_40),
(d_1) <-[:AUTHORED_BY]- (b_40),
(d_2:AUTHOR{name: "SA Khan"}) -[:AUTHORS]-> (b_40),
(d_2) <-[:AUTHORED_BY]- (b_40),
(d_3:AUTHOR{name: "A Sharma"}) -[:AUTHORS]-> (b_40),
(d_3) <-[:AUTHORED_BY]- (b_40),
(d_4:AUTHOR{name: "S Jaebeen"}) -[:AUTHORS]-> (b_40),
(d_4) <-[:AUTHORED_BY]- (b_40),
(d_5:AUTHOR{name: "N Grover"}) -[:AUTHORS]-> (b_40),
(d_5) <-[:AUTHORED_BY]- (b_40),
(b_41:ARTICLE{title: "Total antioxidant property and pH change of dental plaque and saliva in 6-11-year-old children after consumption of flavored milk", id: None}),
(a_2) -[:REFERENCES]-> (b_41),
(a_2) <-[:REFERENCED_BY]- (b_41),
(d_0:AUTHOR{name: "E Khodadadi"}) -[:AUTHORS]-> (b_41),
(d_0) <-[:AUTHORED_BY]- (b_41),
(d_1:AUTHOR{name: "N Ghasemi"}) -[:AUTHORS]-> (b_41),
(d_1) <-[:AUTHORED_BY]- (b_41),
(d_2:AUTHOR{name: "M Pouramir"}) -[:AUTHORS]-> (b_41),
(d_2) <-[:AUTHORED_BY]- (b_41),
(d_3:AUTHOR{name: "A Bijani"}) -[:AUTHORS]-> (b_41),
(d_3) <-[:AUTHORED_BY]- (b_41),
(b_42:ARTICLE{title: "Shah AF. Comparison of changes in salivary pH levels after consumption of plain milk and milk mixed with Sugar. Int Arch Integr Med. 2016;3:174–8.", id: None}),
(a_2) -[:REFERENCES]-> (b_42),
(a_2) <-[:REFERENCED_BY]- (b_42),
(b_43:ARTICLE{title: "Milk, flavoured milk products and caries", id: 11491471}),
(a_2) -[:REFERENCES]-> (b_43),
(a_2) <-[:REFERENCED_BY]- (b_43),
(d_0:AUTHOR{name: "RS Levine"}) -[:AUTHORS]-> (b_43),
(d_0) <-[:AUTHORED_BY]- (b_43),
(b_44:ARTICLE{title: "Effect on salivary pH value after consumption of commercially marketed” Health Drinks”: an in vivo study", id: None}),
(a_2) -[:REFERENCES]-> (b_44),
(a_2) <-[:REFERENCED_BY]- (b_44),
(d_0:AUTHOR{name: "S Bhure"}) -[:AUTHORS]-> (b_44),
(d_0) <-[:AUTHORED_BY]- (b_44),
(d_1:AUTHOR{name: "I Musani"}) -[:AUTHORS]-> (b_44),
(d_1) <-[:AUTHORED_BY]- (b_44),
(d_2:AUTHOR{name: "P Survashe"}) -[:AUTHORS]-> (b_44),
(d_2) <-[:AUTHORED_BY]- (b_44),
(b_45:ARTICLE{title: "Vishalini L, VMRF-DU S, Ramesh M. Comparison of efficacy of salivary ph strips with ph meter using saliva of smokers and non-smokers-a single instituitional study. Journal of Critical Reviews. 2020;7:1522–31.", id: None}),
(a_2) -[:REFERENCES]-> (b_45),
(a_2) <-[:REFERENCED_BY]- (b_45),
(c_0:AUTHOR{name: "Rouaa Zamzam"}) -[:AUTHORS]-> (a_2),
(c_0) <-[:AUTHORED_BY]- (a_2),
(c_1:AUTHOR{name: "Mawia Karkoutly"}) -[:AUTHORS]-> (a_2),
(c_1) <-[:AUTHORED_BY]- (a_2),
(c_2:AUTHOR{name: "Nada Bshara"}) -[:AUTHORS]-> (a_2),
(c_2) <-[:AUTHORED_BY]- (a_2),

(a_3:ARTICLE{title: "Differential abundance of lipids and metabolites related to SARS-CoV-2 infection and susceptibility", id: 10500013}),
(b_0:ARTICLE{title: "SARS-CoV-2 dependence on host pathways", id: 33632832}),
(a_3) -[:REFERENCES]-> (b_0),
(a_3) <-[:REFERENCED_BY]- (b_0),
(d_0:AUTHOR{name: "JP Wong"}) -[:AUTHORS]-> (b_0),
(d_0) <-[:AUTHORED_BY]- (b_0),
(d_1:AUTHOR{name: "B Damania"}) -[:AUTHORS]-> (b_0),
(d_1) <-[:AUTHORED_BY]- (b_0),
(b_1:ARTICLE{title: "A SARS-CoV-2 protein interaction map reveals targets for drug repurposing", id: 32353859}),
(a_3) -[:REFERENCES]-> (b_1),
(a_3) <-[:REFERENCED_BY]- (b_1),
(d_0:AUTHOR{name: "DE Gordon"}) -[:AUTHORS]-> (b_1),
(d_0) <-[:AUTHORED_BY]- (b_1),
(b_2:ARTICLE{title: "Blood molecular markers associated with COVID-19 immunopathology and multi-organ damage", id: None}),
(a_3) -[:REFERENCES]-> (b_2),
(a_3) <-[:REFERENCED_BY]- (b_2),
(d_0:AUTHOR{name: "Y Chen"}) -[:AUTHORS]-> (b_2),
(d_0) <-[:AUTHORED_BY]- (b_2),
(b_3:ARTICLE{title: "Diagnostic potential of the plasma lipidome in infectious disease: Application to acute SARS-CoV-2 infection", id: 34357361}),
(a_3) -[:REFERENCES]-> (b_3),
(a_3) <-[:REFERENCED_BY]- (b_3),
(d_0:AUTHOR{name: "N Gray"}) -[:AUTHORS]-> (b_3),
(d_0) <-[:AUTHORED_BY]- (b_3),
(b_4:ARTICLE{title: "Metabolome analysis for investigating host-gut microbiota interactions", id: 30269936}),
(a_3) -[:REFERENCES]-> (b_4),
(a_3) <-[:REFERENCED_BY]- (b_4),
(d_0:AUTHOR{name: "MX Chen"}) -[:AUTHORS]-> (b_4),
(d_0) <-[:AUTHORED_BY]- (b_4),
(d_1:AUTHOR{name: "S-Y Wang"}) -[:AUTHORS]-> (b_4),
(d_1) <-[:AUTHORED_BY]- (b_4),
(d_2:AUTHOR{name: "C-H Kuo"}) -[:AUTHORS]-> (b_4),
(d_2) <-[:AUTHORED_BY]- (b_4),
(d_3:AUTHOR{name: "I-L Tsai"}) -[:AUTHORS]-> (b_4),
(d_3) <-[:AUTHORED_BY]- (b_4),
(b_5:ARTICLE{title: "Economic burden of COVID-19: A systematic review", id: None}),
(a_3) -[:REFERENCES]-> (b_5),
(a_3) <-[:REFERENCED_BY]- (b_5),
(d_0:AUTHOR{name: "F Richards"}) -[:AUTHORS]-> (b_5),
(d_0) <-[:AUTHORED_BY]- (b_5),
(b_6:ARTICLE{title: "Long-term consequences of COVID-19 at 6 months and above: A systematic review and meta-analysis", id: 35682448}),
(a_3) -[:REFERENCES]-> (b_6),
(a_3) <-[:REFERENCED_BY]- (b_6),
(d_0:AUTHOR{name: "Y Ma"}) -[:AUTHORS]-> (b_6),
(d_0) <-[:AUTHORED_BY]- (b_6),
(b_7:ARTICLE{title: "Global prevalence of post-coronavirus disease 2019 (COVID-19) condition or long COVID: A meta-analysis and systematic review", id: 35429399}),
(a_3) -[:REFERENCES]-> (b_7),
(a_3) <-[:REFERENCED_BY]- (b_7),
(d_0:AUTHOR{name: "C Chen"}) -[:AUTHORS]-> (b_7),
(d_0) <-[:AUTHORED_BY]- (b_7),
(b_8:ARTICLE{title: "Long covid: A systematic review and meta-analysis of 120,970 patients", id: None}),
(a_3) -[:REFERENCES]-> (b_8),
(a_3) <-[:REFERENCED_BY]- (b_8),
(d_0:AUTHOR{name: "F Di Gennaro"}) -[:AUTHORS]-> (b_8),
(d_0) <-[:AUTHORED_BY]- (b_8),
(b_9:ARTICLE{title: "Complex immune dysregulation in COVID-19 patients with severe respiratory failure", id: 32320677}),
(a_3) -[:REFERENCES]-> (b_9),
(a_3) <-[:REFERENCED_BY]- (b_9),
(d_0:AUTHOR{name: "EJ Giamarellos-Bourboulis"}) -[:AUTHORS]-> (b_9),
(d_0) <-[:AUTHORED_BY]- (b_9),
(b_10:ARTICLE{title: "The many faces of the anti-COVID immune response", id: 32353870}),
(a_3) -[:REFERENCES]-> (b_10),
(a_3) <-[:REFERENCED_BY]- (b_10),
(d_0:AUTHOR{name: "SA Vardhana"}) -[:AUTHORS]-> (b_10),
(d_0) <-[:AUTHORED_BY]- (b_10),
(d_1:AUTHOR{name: "JD Wolchok"}) -[:AUTHORS]-> (b_10),
(d_1) <-[:AUTHORED_BY]- (b_10),
(b_11:ARTICLE{title: "The immunology and immunopathology of COVID-19", id: 35271343}),
(a_3) -[:REFERENCES]-> (b_11),
(a_3) <-[:REFERENCED_BY]- (b_11),
(d_0:AUTHOR{name: "M Merad"}) -[:AUTHORS]-> (b_11),
(d_0) <-[:AUTHORED_BY]- (b_11),
(d_1:AUTHOR{name: "CA Blish"}) -[:AUTHORS]-> (b_11),
(d_1) <-[:AUTHORED_BY]- (b_11),
(d_2:AUTHOR{name: "F Sallusto"}) -[:AUTHORS]-> (b_11),
(d_2) <-[:AUTHORED_BY]- (b_11),
(d_3:AUTHOR{name: "A Iwasaki"}) -[:AUTHORS]-> (b_11),
(d_3) <-[:AUTHORED_BY]- (b_11),
(b_12:ARTICLE{title: "Severe covid-19 pneumonia: pathogenesis and clinical management", id: 33692022}),
(a_3) -[:REFERENCES]-> (b_12),
(a_3) <-[:REFERENCED_BY]- (b_12),
(d_0:AUTHOR{name: "AH Attaway"}) -[:AUTHORS]-> (b_12),
(d_0) <-[:AUTHORED_BY]- (b_12),
(d_1:AUTHOR{name: "RG Scheraga"}) -[:AUTHORS]-> (b_12),
(d_1) <-[:AUTHORED_BY]- (b_12),
(d_2:AUTHOR{name: "A Bhimraj"}) -[:AUTHORS]-> (b_12),
(d_2) <-[:AUTHORED_BY]- (b_12),
(d_3:AUTHOR{name: "M Biehl"}) -[:AUTHORS]-> (b_12),
(d_3) <-[:AUTHORED_BY]- (b_12),
(d_4:AUTHOR{name: "U Hatipoğlu"}) -[:AUTHORS]-> (b_12),
(d_4) <-[:AUTHORED_BY]- (b_12),
(b_13:ARTICLE{title: "A comprehensive review on clinical and mechanistic pathophysiological aspects of COVID-19 Malady: How far have we come?", id: 34098986}),
(a_3) -[:REFERENCES]-> (b_13),
(a_3) <-[:REFERENCED_BY]- (b_13),
(d_0:AUTHOR{name: "B Shakaib"}) -[:AUTHORS]-> (b_13),
(d_0) <-[:AUTHORED_BY]- (b_13),
(b_14:ARTICLE{title: "Metabolomics as a powerful tool for diagnostic, pronostic and drug intervention analysis in COVID-19", id: 36876049}),
(a_3) -[:REFERENCES]-> (b_14),
(a_3) <-[:REFERENCED_BY]- (b_14),
(d_0:AUTHOR{name: "C Bruzzone"}) -[:AUTHORS]-> (b_14),
(d_0) <-[:AUTHORED_BY]- (b_14),
(d_1:AUTHOR{name: "R Conde"}) -[:AUTHORS]-> (b_14),
(d_1) <-[:AUTHORED_BY]- (b_14),
(d_2:AUTHOR{name: "N Embade"}) -[:AUTHORS]-> (b_14),
(d_2) <-[:AUTHORED_BY]- (b_14),
(d_3:AUTHOR{name: "JM Mato"}) -[:AUTHORS]-> (b_14),
(d_3) <-[:AUTHORED_BY]- (b_14),
(d_4:AUTHOR{name: "O Millet"}) -[:AUTHORS]-> (b_14),
(d_4) <-[:AUTHORED_BY]- (b_14),
(b_15:ARTICLE{title: "Metabolomic analyses of COVID-19 patients unravel stage-dependent and prognostic biomarkers", id: 33707411}),
(a_3) -[:REFERENCES]-> (b_15),
(a_3) <-[:REFERENCED_BY]- (b_15),
(d_0:AUTHOR{name: "F-X Danlos"}) -[:AUTHORS]-> (b_15),
(d_0) <-[:AUTHORED_BY]- (b_15),
(b_16:ARTICLE{title: "Plasma metabolomic and lipidomic alterations associated with COVID-19", id: 34676128}),
(a_3) -[:REFERENCES]-> (b_16),
(a_3) <-[:REFERENCED_BY]- (b_16),
(d_0:AUTHOR{name: "D Wu"}) -[:AUTHORS]-> (b_16),
(d_0) <-[:AUTHORED_BY]- (b_16),
(b_17:ARTICLE{title: "Dysregulation of lipid metabolism and pathological inflammation in patients with COVID-19", id: 33414495}),
(a_3) -[:REFERENCES]-> (b_17),
(a_3) <-[:REFERENCED_BY]- (b_17),
(d_0:AUTHOR{name: "M Caterino"}) -[:AUTHORS]-> (b_17),
(d_0) <-[:AUTHORED_BY]- (b_17),
(b_18:ARTICLE{title: "Metabolomics study of COVID-19 patients in four different clinical stages", id: 35102215}),
(a_3) -[:REFERENCES]-> (b_18),
(a_3) <-[:REFERENCED_BY]- (b_18),
(d_0:AUTHOR{name: "A Valdés"}) -[:AUTHORS]-> (b_18),
(d_0) <-[:AUTHORED_BY]- (b_18),
(b_19:ARTICLE{title: "Link between serum lipid signature and prognostic factors in COVID-19 patients", id: 34737330}),
(a_3) -[:REFERENCES]-> (b_19),
(a_3) <-[:REFERENCED_BY]- (b_19),
(d_0:AUTHOR{name: "M Dei Cas"}) -[:AUTHORS]-> (b_19),
(d_0) <-[:AUTHORED_BY]- (b_19),
(b_20:ARTICLE{title: "Metabolomics in the diagnosis and prognosis of COVID-19", id: 34367265}),
(a_3) -[:REFERENCES]-> (b_20),
(a_3) <-[:REFERENCED_BY]- (b_20),
(d_0:AUTHOR{name: "MR Hasan"}) -[:AUTHORS]-> (b_20),
(d_0) <-[:AUTHORED_BY]- (b_20),
(d_1:AUTHOR{name: "M Suleiman"}) -[:AUTHORS]-> (b_20),
(d_1) <-[:AUTHORED_BY]- (b_20),
(d_2:AUTHOR{name: "A Pérez-López"}) -[:AUTHORS]-> (b_20),
(d_2) <-[:AUTHORED_BY]- (b_20),
(b_21:ARTICLE{title: "Long COVID: Major findings, mechanisms and recommendations", id: 36639608}),
(a_3) -[:REFERENCES]-> (b_21),
(a_3) <-[:REFERENCED_BY]- (b_21),
(d_0:AUTHOR{name: "HE Davis"}) -[:AUTHORS]-> (b_21),
(d_0) <-[:AUTHORED_BY]- (b_21),
(d_1:AUTHOR{name: "L McCorkell"}) -[:AUTHORS]-> (b_21),
(d_1) <-[:AUTHORED_BY]- (b_21),
(d_2:AUTHOR{name: "JM Vogel"}) -[:AUTHORS]-> (b_21),
(d_2) <-[:AUTHORED_BY]- (b_21),
(d_3:AUTHOR{name: "EJ Topol"}) -[:AUTHORS]-> (b_21),
(d_3) <-[:AUTHORED_BY]- (b_21),
(b_22:ARTICLE{title: "Current understanding of COVID-19 clinical course and investigational treatments", id: None}),
(a_3) -[:REFERENCES]-> (b_22),
(a_3) <-[:REFERENCED_BY]- (b_22),
(d_0:AUTHOR{name: "RB Aguilar"}) -[:AUTHORS]-> (b_22),
(d_0) <-[:AUTHORED_BY]- (b_22),
(b_23:ARTICLE{title: "Metabolic snapshot of plasma samples reveals new pathways implicated in SARS-CoV-2 pathogenesis", id: 35133846}),
(a_3) -[:REFERENCES]-> (b_23),
(a_3) <-[:REFERENCED_BY]- (b_23),
(d_0:AUTHOR{name: "OE Albóniga"}) -[:AUTHORS]-> (b_23),
(d_0) <-[:AUTHORED_BY]- (b_23),
(b_24:ARTICLE{title: "Acute respiratory distress syndrome: New definition, current and future therapeutic options", id: 23825769}),
(a_3) -[:REFERENCES]-> (b_24),
(a_3) <-[:REFERENCED_BY]- (b_24),
(d_0:AUTHOR{name: "V Fanelli"}) -[:AUTHORS]-> (b_24),
(d_0) <-[:AUTHORED_BY]- (b_24),
(b_25:ARTICLE{title: "CDC, Centers for, disease control and prevention, & CDC. Interim Operational Considerations for Public Health Management of Healthcare Workers Exposed to or with Suspected or Confirmed COVID-19: Non-U.S. Healthcare Settings. https://www.cdc.gov/coronavirus/2019-ncov/hcp/non-us-settings/public-health-management-hcwexposed.", id: None}),
(a_3) -[:REFERENCES]-> (b_25),
(a_3) <-[:REFERENCED_BY]- (b_25),
(b_26:ARTICLE{title: "Lejardi, D. & Technologies, A. Improving Coverage of the Plasma Lipidome Using Iterative MS/MS Data Acquisition Combined with Lipid Annotator Software and 6546 LC/Q-TOF. (2020).", id: None}),
(a_3) -[:REFERENCES]-> (b_26),
(a_3) <-[:REFERENCED_BY]- (b_26),
(b_27:ARTICLE{title: "Intra-batch effect correction in liquid chromatography-mass spectrometry using quality control samples and support vector regression (QC-SVRC)", id: 26462549}),
(a_3) -[:REFERENCES]-> (b_27),
(a_3) <-[:REFERENCED_BY]- (b_27),
(d_0:AUTHOR{name: "J Kuligowski"}) -[:AUTHORS]-> (b_27),
(d_0) <-[:AUTHORED_BY]- (b_27),
(d_1:AUTHOR{name: "Á Sánchez-Illana"}) -[:AUTHORS]-> (b_27),
(d_1) <-[:AUTHORED_BY]- (b_27),
(d_2:AUTHOR{name: "D Sanjuán-Herráez"}) -[:AUTHORS]-> (b_27),
(d_2) <-[:AUTHORED_BY]- (b_27),
(d_3:AUTHOR{name: "M Vento"}) -[:AUTHORS]-> (b_27),
(d_3) <-[:AUTHORED_BY]- (b_27),
(d_4:AUTHOR{name: "G Quintás"}) -[:AUTHORS]-> (b_27),
(d_4) <-[:AUTHORED_BY]- (b_27),
(b_28:ARTICLE{title: "CEU mass mediator 3.0: A metabolite annotation tool", id: 30574788}),
(a_3) -[:REFERENCES]-> (b_28),
(a_3) <-[:REFERENCED_BY]- (b_28),
(d_0:AUTHOR{name: "A Gil-de-la-Fuente"}) -[:AUTHORS]-> (b_28),
(d_0) <-[:AUTHORED_BY]- (b_28),
(b_29:ARTICLE{title: "Lipid annotator: Towards accurate annotation in non-targeted liquid chromatography high-resolution tandem mass spectrometry (LC-HRMS/MS) lipidomics using a rapid and user-friendly software", id: 32178227}),
(a_3) -[:REFERENCES]-> (b_29),
(a_3) <-[:REFERENCED_BY]- (b_29),
(d_0:AUTHOR{name: "JP Koelmel"}) -[:AUTHORS]-> (b_29),
(d_0) <-[:AUTHORED_BY]- (b_29),
(b_30:ARTICLE{title: "A lipidome atlas in MS-DIAL 4", id: 32541957}),
(a_3) -[:REFERENCES]-> (b_30),
(a_3) <-[:REFERENCED_BY]- (b_30),
(d_0:AUTHOR{name: "H Tsugawa"}) -[:AUTHORS]-> (b_30),
(d_0) <-[:AUTHORED_BY]- (b_30),
(b_31:ARTICLE{title: "Investigating global lipidome alterations with the lipid network explorer", id: 34436429}),
(a_3) -[:REFERENCES]-> (b_31),
(a_3) <-[:REFERENCED_BY]- (b_31),
(d_0:AUTHOR{name: "N Köhler"}) -[:AUTHORS]-> (b_31),
(d_0) <-[:AUTHORED_BY]- (b_31),
(d_1:AUTHOR{name: "TD Rose"}) -[:AUTHORS]-> (b_31),
(d_1) <-[:AUTHORED_BY]- (b_31),
(d_2:AUTHOR{name: "L Falk"}) -[:AUTHORS]-> (b_31),
(d_2) <-[:AUTHORED_BY]- (b_31),
(d_3:AUTHOR{name: "JK Pauling"}) -[:AUTHORS]-> (b_31),
(d_3) <-[:AUTHORED_BY]- (b_31),
(b_32:ARTICLE{title: "Longitudinal metabolomics of human plasma reveals prognostic markers of COVID-19 disease severity", id: 34308390}),
(a_3) -[:REFERENCES]-> (b_32),
(a_3) <-[:REFERENCED_BY]- (b_32),
(d_0:AUTHOR{name: "M Sindelar"}) -[:AUTHORS]-> (b_32),
(d_0) <-[:AUTHORED_BY]- (b_32),
(b_33:ARTICLE{title: "Metabolic and lipidomic markers differentiate COVID-19 from non-hospitalized and other intensive care patients", id: 34938772}),
(a_3) -[:REFERENCES]-> (b_33),
(a_3) <-[:REFERENCED_BY]- (b_33),
(d_0:AUTHOR{name: "F Schmelter"}) -[:AUTHORS]-> (b_33),
(d_0) <-[:AUTHORED_BY]- (b_33),
(b_34:ARTICLE{title: "Lipidomics revealed plasma phospholipid profile differences between deceased and recovered COVID-19 patients", id: 36291697}),
(a_3) -[:REFERENCES]-> (b_34),
(a_3) <-[:REFERENCED_BY]- (b_34),
(d_0:AUTHOR{name: "N Žarković"}) -[:AUTHORS]-> (b_34),
(d_0) <-[:AUTHORED_BY]- (b_34),
(b_35:ARTICLE{title: "Uneven metabolic and lipidomic profiles in recovered COVID-19 patients as investigated by plasma NMR metabolomics", id: None}),
(a_3) -[:REFERENCES]-> (b_35),
(a_3) <-[:REFERENCED_BY]- (b_35),
(d_0:AUTHOR{name: "M Bizkarguenaga"}) -[:AUTHORS]-> (b_35),
(d_0) <-[:AUTHORED_BY]- (b_35),
(b_36:ARTICLE{title: "Roles of ceramides and other sphingolipids in immune cell function and inflammation", id: None}),
(a_3) -[:REFERENCES]-> (b_36),
(a_3) <-[:REFERENCED_BY]- (b_36),
(d_0:AUTHOR{name: "S Albeituni"}) -[:AUTHORS]-> (b_36),
(d_0) <-[:AUTHORED_BY]- (b_36),
(d_1:AUTHOR{name: "J Stiban"}) -[:AUTHORS]-> (b_36),
(d_1) <-[:AUTHORED_BY]- (b_36),
(d_2:AUTHOR{name: "KV Honn"}) -[:AUTHORS]-> (b_36),
(d_2) <-[:AUTHORED_BY]- (b_36),
(d_3:AUTHOR{name: "DC Zeldin"}) -[:AUTHORS]-> (b_36),
(d_3) <-[:AUTHORED_BY]- (b_36),
(b_37:ARTICLE{title: "Ceramide-1-phosphate promotes cell survival through activation of the phosphatidylinositol 3-kinase/protein kinase B pathway", id: 15978590}),
(a_3) -[:REFERENCES]-> (b_37),
(a_3) <-[:REFERENCED_BY]- (b_37),
(d_0:AUTHOR{name: "A Gómez-Muñoz"}) -[:AUTHORS]-> (b_37),
(d_0) <-[:AUTHORED_BY]- (b_37),
(b_38:ARTICLE{title: "n-3 polyunsaturated fatty acids suppress CD4+ T cell proliferation by altering phosphatidylinositol-(4,5)-bisphosphate [PI(4,5)P2] organization", id: None}),
(a_3) -[:REFERENCES]-> (b_38),
(a_3) <-[:REFERENCED_BY]- (b_38),
(d_0:AUTHOR{name: "TY Hou"}) -[:AUTHORS]-> (b_38),
(d_0) <-[:AUTHORED_BY]- (b_38),
(b_39:ARTICLE{title: "Inferring a causal relationship between ceramide levels and COVID-19 respiratory distress", id: 34675292}),
(a_3) -[:REFERENCES]-> (b_39),
(a_3) <-[:REFERENCED_BY]- (b_39),
(d_0:AUTHOR{name: "MM Khodadoust"}) -[:AUTHORS]-> (b_39),
(d_0) <-[:AUTHORED_BY]- (b_39),
(b_40:ARTICLE{title: "Acute kidney injury in severe COVID-19 has similarities to sepsis-associated kidney injury", id: 34425963}),
(a_3) -[:REFERENCES]-> (b_40),
(a_3) <-[:REFERENCED_BY]- (b_40),
(d_0:AUTHOR{name: "MP Alexander"}) -[:AUTHORS]-> (b_40),
(d_0) <-[:AUTHORED_BY]- (b_40),
(b_41:ARTICLE{title: "The acid sphingomyelinase/ceramide system in COVID-19", id: 34608263}),
(a_3) -[:REFERENCES]-> (b_41),
(a_3) <-[:REFERENCED_BY]- (b_41),
(d_0:AUTHOR{name: "J Kornhuber"}) -[:AUTHORS]-> (b_41),
(d_0) <-[:AUTHORED_BY]- (b_41),
(d_1:AUTHOR{name: "N Hoertel"}) -[:AUTHORS]-> (b_41),
(d_1) <-[:AUTHORED_BY]- (b_41),
(d_2:AUTHOR{name: "E Gulbins"}) -[:AUTHORS]-> (b_41),
(d_2) <-[:AUTHORED_BY]- (b_41),
(b_42:ARTICLE{title: "Marked elevations in lung and plasma ceramide in COVID-19 linked to microvascular injury", id: 37212278}),
(a_3) -[:REFERENCES]-> (b_42),
(a_3) <-[:REFERENCED_BY]- (b_42),
(d_0:AUTHOR{name: "I Petrache"}) -[:AUTHORS]-> (b_42),
(d_0) <-[:AUTHORED_BY]- (b_42),
(b_43:ARTICLE{title: "Sphingolipids as modulators of SARS-CoV-2 infection", id: 34222257}),
(a_3) -[:REFERENCES]-> (b_43),
(a_3) <-[:REFERENCED_BY]- (b_43),
(d_0:AUTHOR{name: "K Törnquist"}) -[:AUTHORS]-> (b_43),
(d_0) <-[:AUTHORED_BY]- (b_43),
(d_1:AUTHOR{name: "MY Asghar"}) -[:AUTHORS]-> (b_43),
(d_1) <-[:AUTHORED_BY]- (b_43),
(d_2:AUTHOR{name: "V Srinivasan"}) -[:AUTHORS]-> (b_43),
(d_2) <-[:AUTHORED_BY]- (b_43),
(d_3:AUTHOR{name: "L Korhonen"}) -[:AUTHORS]-> (b_43),
(d_3) <-[:AUTHORED_BY]- (b_43),
(d_4:AUTHOR{name: "D Lindholm"}) -[:AUTHORS]-> (b_43),
(d_4) <-[:AUTHORED_BY]- (b_43),
(b_44:ARTICLE{title: "Omics-driven systems interrogation of metabolic dysregulation in COVID-19 pathogenesis", id: 32610096}),
(a_3) -[:REFERENCES]-> (b_44),
(a_3) <-[:REFERENCED_BY]- (b_44),
(d_0:AUTHOR{name: "J-W Song"}) -[:AUTHORS]-> (b_44),
(d_0) <-[:AUTHORED_BY]- (b_44),
(b_45:ARTICLE{title: "Development of a multiomics model for identification of predictive biomarkers for COVID-19 severity: A retrospective cohort study", id: 35835712}),
(a_3) -[:REFERENCES]-> (b_45),
(a_3) <-[:REFERENCED_BY]- (b_45),
(d_0:AUTHOR{name: "SK Byeon"}) -[:AUTHORS]-> (b_45),
(d_0) <-[:AUTHORED_BY]- (b_45),
(b_46:ARTICLE{title: "Dynamic modulations of sphingolipids and glycerophospholipids in COVID-19", id: None}),
(a_3) -[:REFERENCES]-> (b_46),
(a_3) <-[:REFERENCED_BY]- (b_46),
(d_0:AUTHOR{name: "M Kurano"}) -[:AUTHORS]-> (b_46),
(d_0) <-[:AUTHORED_BY]- (b_46),
(b_47:ARTICLE{title: "Alterations in the human oral and gut microbiomes and lipidomics in COVID-19", id: 33789966}),
(a_3) -[:REFERENCES]-> (b_47),
(a_3) <-[:REFERENCED_BY]- (b_47),
(d_0:AUTHOR{name: "Z Ren"}) -[:AUTHORS]-> (b_47),
(d_0) <-[:AUTHORED_BY]- (b_47),
(b_48:ARTICLE{title: "Metabolomics analysis reveals a modified amino acid metabolism that correlates with altered oxygen homeostasis in COVID-19 patients", id: 33737694}),
(a_3) -[:REFERENCES]-> (b_48),
(a_3) <-[:REFERENCED_BY]- (b_48),
(d_0:AUTHOR{name: "JC Páez-Franco"}) -[:AUTHORS]-> (b_48),
(d_0) <-[:AUTHORED_BY]- (b_48),
(b_49:ARTICLE{title: "α-Hydroxybutyric acid is a selective metabolite biomarker of impaired glucose tolerance", id: 27208342}),
(a_3) -[:REFERENCES]-> (b_49),
(a_3) <-[:REFERENCED_BY]- (b_49),
(d_0:AUTHOR{name: "J Cobb"}) -[:AUTHORS]-> (b_49),
(d_0) <-[:AUTHORED_BY]- (b_49),
(b_50:ARTICLE{title: "Dissecting lipid metabolism alterations in SARS-CoV-2", id: 33571544}),
(a_3) -[:REFERENCES]-> (b_50),
(a_3) <-[:REFERENCED_BY]- (b_50),
(d_0:AUTHOR{name: "I Casari"}) -[:AUTHORS]-> (b_50),
(d_0) <-[:AUTHORED_BY]- (b_50),
(d_1:AUTHOR{name: "M Manfredi"}) -[:AUTHORS]-> (b_50),
(d_1) <-[:AUTHORED_BY]- (b_50),
(d_2:AUTHOR{name: "P Metharom"}) -[:AUTHORS]-> (b_50),
(d_2) <-[:AUTHORED_BY]- (b_50),
(d_3:AUTHOR{name: "M Falasca"}) -[:AUTHORS]-> (b_50),
(d_3) <-[:AUTHORED_BY]- (b_50),
(b_51:ARTICLE{title: "The serum metabolome of COVID-19 patients is distinctive and predictive", id: 33662365}),
(a_3) -[:REFERENCES]-> (b_51),
(a_3) <-[:REFERENCED_BY]- (b_51),
(d_0:AUTHOR{name: "D Shi"}) -[:AUTHORS]-> (b_51),
(d_0) <-[:AUTHORED_BY]- (b_51),
(b_52:ARTICLE{title: "Association of COVID-19 with hepatic metabolic dysfunction", id: 36188741}),
(a_3) -[:REFERENCES]-> (b_52),
(a_3) <-[:REFERENCED_BY]- (b_52),
(d_0:AUTHOR{name: "R Kumar"}) -[:AUTHORS]-> (b_52),
(d_0) <-[:AUTHORED_BY]- (b_52),
(d_1:AUTHOR{name: "V Kumar"}) -[:AUTHORS]-> (b_52),
(d_1) <-[:AUTHORED_BY]- (b_52),
(d_2:AUTHOR{name: "R Arya"}) -[:AUTHORS]-> (b_52),
(d_2) <-[:AUTHORED_BY]- (b_52),
(d_3:AUTHOR{name: "U Anand"}) -[:AUTHORS]-> (b_52),
(d_3) <-[:AUTHORED_BY]- (b_52),
(d_4:AUTHOR{name: "RN Priyadarshi"}) -[:AUTHORS]-> (b_52),
(d_4) <-[:AUTHORED_BY]- (b_52),
(b_53:ARTICLE{title: "Redefining COVID-19 severity and prognosis: The role of clinical and immunobiotypes", id: 34566957}),
(a_3) -[:REFERENCES]-> (b_53),
(a_3) <-[:REFERENCED_BY]- (b_53),
(d_0:AUTHOR{name: "J Torres-Ruiz"}) -[:AUTHORS]-> (b_53),
(d_0) <-[:AUTHORED_BY]- (b_53),
(b_54:ARTICLE{title: "Large-scale plasma analysis revealed new mechanisms and molecules associated with the host response to SARS-CoV-2", id: 33207699}),
(a_3) -[:REFERENCES]-> (b_54),
(a_3) <-[:REFERENCED_BY]- (b_54),
(d_0:AUTHOR{name: "E Barberis"}) -[:AUTHORS]-> (b_54),
(d_0) <-[:AUTHORED_BY]- (b_54),
(b_55:ARTICLE{title: "Large-scale plasma analysis revealed new mechanisms and molecules associated with the host response to sars-cov-2", id: None}),
(a_3) -[:REFERENCES]-> (b_55),
(a_3) <-[:REFERENCED_BY]- (b_55),
(d_0:AUTHOR{name: "E Barberis"}) -[:AUTHORS]-> (b_55),
(d_0) <-[:AUTHORED_BY]- (b_55),
(b_56:ARTICLE{title: "Severity of COVID-19 patients predicted by serum sphingolipids signature", id: 34638539}),
(a_3) -[:REFERENCES]-> (b_56),
(a_3) <-[:REFERENCED_BY]- (b_56),
(d_0:AUTHOR{name: "E Torretta"}) -[:AUTHORS]-> (b_56),
(d_0) <-[:AUTHORED_BY]- (b_56),
(b_57:ARTICLE{title: "HMDB. Human Metabolome Database: Showing metabocard for Aminomalonic acid (HMDB0001147). https://hmdb.ca/metabolites/HMDB0001147.", id: None}),
(a_3) -[:REFERENCES]-> (b_57),
(a_3) <-[:REFERENCED_BY]- (b_57),
(b_58:ARTICLE{title: "In vitro effects of monolaurin compounds on enveloped RNA and DNA viruses", id: 32336838}),
(a_3) -[:REFERENCES]-> (b_58),
(a_3) <-[:REFERENCED_BY]- (b_58),
(d_0:AUTHOR{name: "JC Hierholzer"}) -[:AUTHORS]-> (b_58),
(d_0) <-[:AUTHORED_BY]- (b_58),
(d_1:AUTHOR{name: "JJ Kabara"}) -[:AUTHORS]-> (b_58),
(d_1) <-[:AUTHORED_BY]- (b_58),
(b_59:ARTICLE{title: "Loss of furin cleavage site attenuates SARS-CoV-2 pathogenesis", id: 33494095}),
(a_3) -[:REFERENCES]-> (b_59),
(a_3) <-[:REFERENCED_BY]- (b_59),
(d_0:AUTHOR{name: "BA Johnson"}) -[:AUTHORS]-> (b_59),
(d_0) <-[:AUTHORED_BY]- (b_59),
(b_60:ARTICLE{title: "Distinctive roles of furin and TMPRSS2 in SARS-CoV-2 infectivity", id: 35343766}),
(a_3) -[:REFERENCES]-> (b_60),
(a_3) <-[:REFERENCED_BY]- (b_60),
(d_0:AUTHOR{name: "R Essalmani"}) -[:AUTHORS]-> (b_60),
(d_0) <-[:AUTHORED_BY]- (b_60),
(b_61:ARTICLE{title: "Untargeted detection of the carbonyl metabolome by chemical derivatization and liquid chromatography-tandem mass spectrometry in precursor ion scan mode: Elucidation of COVID-19 severity biomarkers", id: 35151400}),
(a_3) -[:REFERENCES]-> (b_61),
(a_3) <-[:REFERENCED_BY]- (b_61),
(d_0:AUTHOR{name: "A Gomez-Gomez"}) -[:AUTHORS]-> (b_61),
(d_0) <-[:AUTHORED_BY]- (b_61),
(b_62:ARTICLE{title: "HMDB. Human Metabolome Database: Showing Metabocard for Threonic acid (HMDB0000943). https://hmdb.ca/metabolites/HMDB0000943.", id: None}),
(a_3) -[:REFERENCES]-> (b_62),
(a_3) <-[:REFERENCED_BY]- (b_62),
(b_63:ARTICLE{title: "Vitamin C in the treatment of COVID-19", id: 33916257}),
(a_3) -[:REFERENCES]-> (b_63),
(a_3) <-[:REFERENCED_BY]- (b_63),
(d_0:AUTHOR{name: "GP Milani"}) -[:AUTHORS]-> (b_63),
(d_0) <-[:AUTHORED_BY]- (b_63),
(d_1:AUTHOR{name: "M Macchi"}) -[:AUTHORS]-> (b_63),
(d_1) <-[:AUTHORED_BY]- (b_63),
(d_2:AUTHOR{name: "A Guz-Mark"}) -[:AUTHORS]-> (b_63),
(d_2) <-[:AUTHORED_BY]- (b_63),
(b_64:ARTICLE{title: "Vitamin C and D supplementation and the severity of COVID-19: A protocol for systematic review and meta-analysis", id: 34190164}),
(a_3) -[:REFERENCES]-> (b_64),
(a_3) <-[:REFERENCED_BY]- (b_64),
(d_0:AUTHOR{name: "GAS Toscano"}) -[:AUTHORS]-> (b_64),
(d_0) <-[:AUTHORED_BY]- (b_64),
(d_1:AUTHOR{name: "II de Araújo"}) -[:AUTHORS]-> (b_64),
(d_1) <-[:AUTHORED_BY]- (b_64),
(d_2:AUTHOR{name: "TA de Souza"}) -[:AUTHORS]-> (b_64),
(d_2) <-[:AUTHORED_BY]- (b_64),
(d_3:AUTHOR{name: "IR Barbosa Mirabal"}) -[:AUTHORS]-> (b_64),
(d_3) <-[:AUTHORED_BY]- (b_64),
(d_4:AUTHOR{name: "G de Vasconcelos Torres"}) -[:AUTHORS]-> (b_64),
(d_4) <-[:AUTHORED_BY]- (b_64),
(b_65:ARTICLE{title: "Cholesterol, lipoproteins, and COVID-19: Basic concepts and clinical applications", id: None}),
(a_3) -[:REFERENCES]-> (b_65),
(a_3) <-[:REFERENCED_BY]- (b_65),
(d_0:AUTHOR{name: "E Kočar"}) -[:AUTHORS]-> (b_65),
(d_0) <-[:AUTHORED_BY]- (b_65),
(d_1:AUTHOR{name: "T Režen"}) -[:AUTHORS]-> (b_65),
(d_1) <-[:AUTHORED_BY]- (b_65),
(d_2:AUTHOR{name: "D Rozman"}) -[:AUTHORS]-> (b_65),
(d_2) <-[:AUTHORED_BY]- (b_65),
(b_66:ARTICLE{title: "Virus infection and lipid rafts", id: 16880600}),
(a_3) -[:REFERENCES]-> (b_66),
(a_3) <-[:REFERENCED_BY]- (b_66),
(d_0:AUTHOR{name: "T Suzuki"}) -[:AUTHORS]-> (b_66),
(d_0) <-[:AUTHORED_BY]- (b_66),
(d_1:AUTHOR{name: "Y Suzuki"}) -[:AUTHORS]-> (b_66),
(d_1) <-[:AUTHORED_BY]- (b_66),
(c_0:AUTHOR{name: "Oihane E. Albóniga"}) -[:AUTHORS]-> (a_3),
(c_0) <-[:AUTHORED_BY]- (a_3),
(c_1:AUTHOR{name: "Elena Moreno"}) -[:AUTHORS]-> (a_3),
(c_1) <-[:AUTHORED_BY]- (a_3),
(c_2:AUTHOR{name: "Santiago Moreno"}) -[:AUTHORS]-> (a_3),
(c_2) <-[:AUTHORED_BY]- (a_3),
(c_3:AUTHOR{name: "Coral Barbas"}) -[:AUTHORS]-> (a_3),
(c_3) <-[:AUTHORED_BY]- (a_3),
(c_4:AUTHOR{name: "Sergio Serrano-Villar"}) -[:AUTHORS]-> (a_3),
(c_4) <-[:AUTHORED_BY]- (a_3),
(c_5:AUTHOR{name: "Sergio Serrano-Villar"}) -[:AUTHORS]-> (a_3),
(c_5) <-[:AUTHORED_BY]- (a_3),
(c_6:AUTHOR{name: "Sergio Serrano-Villar"}) -[:AUTHORS]-> (a_3),
(c_6) <-[:AUTHORED_BY]- (a_3),
(c_7:AUTHOR{name: "Sergio Serrano-Villar"}) -[:AUTHORS]-> (a_3),
(c_7) <-[:AUTHORED_BY]- (a_3),
(c_8:AUTHOR{name: "Javier Martínez-Sanz"}) -[:AUTHORS]-> (a_3),
(c_8) <-[:AUTHORED_BY]- (a_3),
(c_9:AUTHOR{name: "Pilar Vizcarra"}) -[:AUTHORS]-> (a_3),
(c_9) <-[:AUTHORED_BY]- (a_3),
(c_10:AUTHOR{name: "Raquel Ron"}) -[:AUTHORS]-> (a_3),
(c_10) <-[:AUTHORED_BY]- (a_3),
(c_11:AUTHOR{name: "Jorge Díaz-Álvarez"}) -[:AUTHORS]-> (a_3),
(c_11) <-[:AUTHORED_BY]- (a_3),
(c_12:AUTHOR{name: "Marta Rosas Cancio-Suarez"}) -[:AUTHORS]-> (a_3),
(c_12) <-[:AUTHORED_BY]- (a_3),
(c_13:AUTHOR{name: "Matilde Sánchez-Conde"}) -[:AUTHORS]-> (a_3),
(c_13) <-[:AUTHORED_BY]- (a_3),
(c_14:AUTHOR{name: "Juan Carlos Galán"}) -[:AUTHORS]-> (a_3),
(c_14) <-[:AUTHORED_BY]- (a_3),
(c_15:AUTHOR{name: "Santiago Angulo"}) -[:AUTHORS]-> (a_3),
(c_15) <-[:AUTHORED_BY]- (a_3),

